package com.jojo.game.presentation.scenario.evidence

internal fun appendHelperPart2(writer: ScenarioHelperEventWriter) = with(writer) {
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            566.646f,
            400.0f,
            160.0f,
            63.0f,
            null,
            "DEBUFF",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            726.646f,
            400.0f,
            229.83f,
            63.0f,
            null,
            "를 표시합니다.",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            165.686f,
            350.0f,
            34.6f,
            63.0f,
            null,
            "☆",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            200.286f,
            350.0f,
            91.43f,
            63.0f,
            null,
            " 번호 ",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            291.716f,
            350.0f,
            22.25f,
            63.0f,
            null,
            "7",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            313.966f,
            350.0f,
            746.31f,
            63.0f,
            null,
            ": 왼쪽 하단에 캐릭터 능력과 장비를 표시합니다.",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            165.686f,
            300.0f,
            34.6f,
            63.0f,
            null,
            "☆",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            200.286f,
            300.0f,
            91.43f,
            63.0f,
            null,
            " 숫자 ",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            291.716f,
            300.0f,
            22.25f,
            63.0f,
            null,
            "8",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            313.966f,
            300.0f,
            861.22f,
            63.0f,
            null,
            ": 더블 히트의 치명타 확률과 카운터 관계를 표시합니다.",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            165.686f,
            250.0f,
            34.6f,
            63.0f,
            null,
            "☆",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            200.286f,
            250.0f,
            91.43f,
            63.0f,
            null,
            " 번호 ",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            291.716f,
            250.0f,
            22.25f,
            63.0f,
            null,
            "9",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            313.966f,
            250.0f,
            607.91f,
            63.0f,
            null,
            ": 지형 적응 및 이동 비용을 표시합니다.",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            165.686f,
            200.0f,
            34.6f,
            63.0f,
            null,
            "☆",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            200.286f,
            200.0f,
            91.43f,
            63.0f,
            null,
            " 문자 ",
            true
        )
}
