package com.jojo.game.presentation.scenario.evidence

internal fun appendHelperPart5(writer: ScenarioHelperEventWriter) = with(writer) {
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            165.686f,
            -300.0f,
            34.6f,
            63.0f,
            null,
            "☆",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            200.286f,
            -300.0f,
            91.43f,
            63.0f,
            null,
            " 문자 ",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            291.716f,
            -300.0f,
            24.43f,
            63.0f,
            null,
            "Z",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            316.146f,
            -300.0f,
            608.85f,
            63.0f,
            null,
            ": 초가속, 그리고 Z 버튼을 눌러서 취소.",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            165.686f,
            -350.0f,
            34.6f,
            63.0f,
            null,
            "☆",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            200.286f,
            -350.0f,
            11.11f,
            63.0f,
            null,
            " ",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            211.396f,
            -350.0f,
            80.04f,
            63.0f,
            null,
            "Shift",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            291.436f,
            -350.0f,
            963.78f,
            63.0f,
            null,
            ": 스토리 대사를 전속력으로 건너뛰고, 숫자 0을 초기화하세요.",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            165.686f,
            -400.0f,
            34.6f,
            63.0f,
            null,
            "☆",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            200.286f,
            -400.0f,
            11.11f,
            63.0f,
            null,
            " ",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            211.396f,
            -400.0f,
            160.63f,
            63.0f,
            null,
            " 화살표 키",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            372.026f,
            -400.0f,
            760.61f,
            63.0f,
            null,
            ": S가 전장에 있을 때 창 화면 크기를 변경합니다.",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            165.686f,
            -450.0f,
            34.6f,
            63.0f,
            null,
            "☆",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            200.286f,
            -450.0f,
            11.11f,
            63.0f,
            null,
            " ",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            211.396f,
            -450.0f,
            299.85f,
            63.0f,
            null,
            " 왼쪽 키보드 + - 키",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            511.246f,
            -450.0f,
            285.08f,
            63.0f,
            null,
            ": BGM 볼륨 조절.",
            false
        )
}
