package com.jojo.game.verification.scenario.evidence

import com.jojo.game.presentation.scenario.*

internal fun appendHelperPart4(writer: ScenarioHelperEventWriter) = with(writer) {
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            200.286f,
            -50.0f,
            91.43f,
            63.0f,
            null,
            " 문자 ",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            291.716f,
            -50.0f,
            26.68f,
            63.0f,
            null,
            "E",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            318.396f,
            -50.0f,
            918.05f,
            63.0f,
            null,
            ": 아군 클릭 후 제어 불가능한 유닛 행동 명령이 표시됩니다.",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            165.686f,
            -100.0f,
            34.6f,
            63.0f,
            null,
            "☆",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            200.286f,
            -100.0f,
            91.43f,
            63.0f,
            null,
            " 편지 ",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            291.716f,
            -100.0f,
            24.43f,
            63.0f,
            null,
            "F",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            316.146f,
            -100.0f,
            987.25f,
            63.0f,
            null,
            ": 통제 불가능한 유닛을 클릭하면 다른 유닛에 대한 증오 수치를 ",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            165.686f,
            -150.0f,
            149.51f,
            63.0f,
            null,
            "표시한다.",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            165.686f,
            -200.0f,
            34.6f,
            63.0f,
            null,
            "☆",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            200.286f,
            -200.0f,
            91.43f,
            63.0f,
            null,
            " 글자 ",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            291.716f,
            -200.0f,
            31.11f,
            63.0f,
            null,
            "G",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            322.826f,
            -200.0f,
            906.93f,
            63.0f,
            null,
            ": 아군을 클릭한 후 빨간색으로 표시하고 적군 수 있습니다.",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            165.686f,
            -250.0f,
            34.6f,
            63.0f,
            null,
            "☆",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            200.286f,
            -250.0f,
            91.43f,
            63.0f,
            null,
            " 문자 ",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            291.716f,
            -250.0f,
            28.89f,
            63.0f,
            null,
            "H",
            false
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            320.606f,
            -250.0f,
            505.37f,
            63.0f,
            null,
            ": 업그레이드 정보를 표시합니다.",
            false
        )
}
