// Verification
package com.jojo.game.verification.scenario.evidence

import com.jojo.game.presentation.scenario.*

/** appendHelperPart3: 검증 이벤트와 산출물을 기록한다. */
internal fun appendHelperPart3(writer: ScenarioHelperEventWriter) = with(writer) {
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            291.716f,
            200.0f,
            26.68f,
            63.0f,
            null,
            "A",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            318.396f,
            200.0f,
            857.24f,
            63.0f,
            null,
            ": 턴 시작 시 자동으로 저장되며, 저장 시퀀스 881-900.",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            165.686f,
            150.0f,
            34.6f,
            63.0f,
            null,
            "☆",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            200.286f,
            150.0f,
            91.43f,
            63.0f,
            null,
            " 문자 ",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            291.716f,
            150.0f,
            26.68f,
            63.0f,
            null,
            "B",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            318.396f,
            150.0f,
            999.62f,
            63.0f,
            null,
            ": 속성 인터페이스는 모든 가능한 전략과 학습 수준을 표시합니다",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            165.686f,
            100.0f,
            11.11f,
            63.0f,
            null,
            ".",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            165.686f,
            50.0f,
            34.6f,
            63.0f,
            null,
            "☆",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            200.286f,
            50.0f,
            91.43f,
            63.0f,
            null,
            " 글자 ",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            291.716f,
            50.0f,
            28.89f,
            63.0f,
            null,
            "C",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            320.606f,
            50.0f,
            505.37f,
            63.0f,
            null,
            ": 공격자의 스트로크를 표시한다.",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            165.686f,
            0.0f,
            34.6f,
            63.0f,
            null,
            "☆",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            200.286f,
            0.0f,
            91.43f,
            63.0f,
            null,
            " 문자 ",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            291.716f,
            0.0f,
            28.89f,
            63.0f,
            null,
            "D",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            320.606f,
            0.0f,
            918.05f,
            63.0f,
            null,
            ": 자동 장착 시 강제 배치 불가의 장비를 제거하지 않습니다.",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            165.686f,
            -50.0f,
            34.6f,
            63.0f,
            null,
            "☆",
            true
        )
}
