package com.jojo.game.verification.scenario.evidence

import com.jojo.game.presentation.scenario.*

internal fun appendHelperPart1(writer: ScenarioHelperEventWriter) = with(writer) {
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            646.056f,
            550.0f,
            286.65f,
            63.0f,
            null,
            "가 원래 속도이며, ",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            932.706f,
            550.0f,
            57.81f,
            63.0f,
            null,
            "1-4",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            990.516f,
            550.0f,
            137.14f,
            63.0f,
            null,
            "가 가속, ",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            1127.656f,
            550.0f,
            22.25f,
            63.0f,
            null,
            "1",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            1149.906f,
            550.0f,
            160.63f,
            63.0f,
            null,
            "이 가장 빠",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            165.686f,
            500.0f,
            114.91f,
            63.0f,
            null,
            "릅니다.",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            165.686f,
            450.0f,
            34.6f,
            63.0f,
            null,
            "☆",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            200.286f,
            450.0f,
            91.43f,
            63.0f,
            null,
            " 번호 ",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            291.716f,
            450.0f,
            22.25f,
            63.0f,
            null,
            "5",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            313.966f,
            450.0f,
            757.42f,
            63.0f,
            null,
            ": 진영에 따라 다른 색상의 체력 바를 표시합니다.",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            165.686f,
            400.0f,
            34.6f,
            63.0f,
            null,
            "☆",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            200.286f,
            400.0f,
            91.43f,
            63.0f,
            null,
            " 번호 ",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            291.716f,
            400.0f,
            22.25f,
            63.0f,
            null,
            "6",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            313.966f,
            400.0f,
            102.54f,
            63.0f,
            null,
            ": 문자 ",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            416.506f,
            400.0f,
            104.43f,
            63.0f,
            null,
            "BUFF",
            true
        )
        draw(
            "Canvas/Layer/Logo_12-1/scrollview/view/content/richtext/RICHTEXT_CHILD",
            "label",
            520.936f,
            400.0f,
            45.71f,
            63.0f,
            null,
            "와 ",
            true
        )
}
