#!/usr/bin/env node
/* Direct recovered factory trace for the auto-battle cancellation overlay and
 * its actual option owner, MsgBox4.  TuoGuanLayer itself has no option state. */
const fs=require('fs'),path=require('path'),F=JSON.parse(fs.readFileSync(process.argv[2]));
function N(){this.tag2=0;this.active=true;this.position={x:0}} function L(){this.node=new N();this.string=''} function T(){this.isChecked=false;this.check=()=>this.isChecked=true;this.uncheck=()=>this.isChecked=false}
function U(){this.node=new N();this.nodes={};this.comps={};this.removed=0;this.events=[]} U.prototype._setBg=function(){};U.prototype.seekNodeByName=function(n){return this.nodes[n]||(this.nodes[n]=new N())};U.prototype.seekCompByName=function(K,n,p){let k=n+(p?'x':'');return this.comps[k]||(this.comps[k]=new K())};U.prototype.addTouchEventListener=function(n,f,p){n.listener=f;n.priority=p};U.prototype.removeFromParent=function(){this.removed++};U.prototype.dispatchEvent=function(n){this.events.push(n)};U.prototype.cmdToast=function(){};
global.cc={_RF:{push(){},pop(){}},_decorator:{ccclass:x=>x,property:()=>()=>{}},Label:L,Toggle:T};
function load(f,deps){let e={};require(path.resolve(__dirname,'../../jojo_mobile/sgccz-desktop/recovered-js/modules/ui/'+f+'.js'))(n=>deps[n]||{default:{}},{},e);return e.default}
const store={value:0,getIntegerForKey(){return this.value},setIntegerForKey(_,v){this.value=v}};const Msg=load('MsgBox',{UILayer:{default:U},Config:{Z_INDEX:{MSGBOX:10}}});const Msg4=load('MsgBox4',{MsgBox:{default:Msg},UserDefault:{default:{getInstance:()=>store}}});const TG=load('TuoGuanLayer',{UILayer:{default:U}});
function run(c){store.value=c.stored||0;let x,calls=[];const create=()=>{x=c.kind==='tuoguan'?new TG():new Msg4();x.onCreate(c.kind==='tuoguan'?undefined:{flag:c.flag,fn:v=>calls.push(v)})};create();const snap=step=>({step,attached:x.removed===0,dispatches:[...x.events],calls:[...calls],checked:x.tuoguan?.isChecked??null,stored:store.value,cancelPriority:x.nodes.Panel_cancel?.priority??null});let out=[snap('create')];for(const e of c.events){let p=e.split(':');if(p[0]==='cancel')x.nodes.Panel_cancel.listener(x.nodes.Panel_cancel,+p[1]);else if(p[0]==='button'){let n=x.seekNodeByName('bg0/btns/button'+p[1]);if(!n.listener)throw Error(JSON.stringify([Object.keys(x.nodes),c,e]));n.listener(n,+p[2])}else if(p[0]==='toggle')x.tuoguan.isChecked=p[1]==='1';else if(p[0]==='recreate')create();out.push(snap(e))}return out}
fs.mkdirSync(path.dirname(process.argv[3]),{recursive:true});fs.writeFileSync(process.argv[3],JSON.stringify(Object.fromEntries(F.cases.map(c=>[c.name,run(c)]))));
