#!/usr/bin/env node
/* Actual recovered Battle.js/BattleConfg.js factory runner.  UIScene and
 * persistence are explicit Cocos-boundary mocks; their calls are trace data. */
const fs=require('fs'),path=require('path'),F=JSON.parse(fs.readFileSync(process.argv[2]));
global.cc={_RF:{push(){},pop(){}},_decorator:{ccclass:x=>x,property:()=>()=>{}},Prefab:class{},SpriteFrame:class{},Texture2D:class{}};
function Scene(){this.layers=[];this.listeners={};this.m_manager={saveGame:(idx,data)=>this.log.push('manager.saveGame:'+idx+':'+data)};this.log=[]}Scene.prototype.addLayer=function(id,arg){this.layers.push({id,args:arg&&typeof arg==='object'?{ms:arg.ms??null,es:arg.es??null,flag:arg.flag??null}:arg??null});if(id===Battle.LAYER.BattleScreen)return this.mockBattle};Scene.prototype.addEventListener=function(name,fn){this.listeners[name]=fn};
let saves=[];const model={save:x=>{x.modelSaved=true;saves.push('model.save')}};function factory(file,deps){let e={};require(path.resolve(__dirname,'../../jojo_mobile/sgccz-desktop/recovered-js/modules/battle/'+file))(n=>deps[n]||{}, {}, e);return e}
const Battle=factory('Battle.js',{UIScene:{default:Scene},Instance:{default:{LAYER:{ForcesListLayer:'ForcesListLayer'}}},Model:{default:{instance:()=>model}}}).default;const Confg=factory('BattleConfg.js',{});
function numeric(v){return Object.fromEntries(Object.entries(v).filter(([k,x])=>Number.isNaN(+k)&&typeof x==='number'))}const constants=Object.fromEntries(Object.entries(Confg).filter(([,v])=>v&&typeof v==='object').map(([k,v])=>[k,numeric(v)]));
function run(c){saves=[];const b=new Battle();b.mockBattle={save:o=>{o.battleSaved=true;b.log.push('battle.save')},filterUnits:id=>id===1187?['m1','m2']:['e1']};b.onCreate({scenario:1});b.battleLayer='prefab:battle';b.battleInitLayer='prefab:init';b.miniMapLayer='prefab:mini';b.noticeInfoLayer='prefab:notice';const resources=[];const callbacks=[];for(const event of c.events){const [kind,value]=event.split(':');if(kind==='resource')resources.push([value,b.getResource(value)??null]);else if(kind==='save')b.listeners.SAVE_GAME({idx:+value,func:()=>callbacks.push('save.callback')});else if(kind==='forces')b.listeners.SHOW_CHARACTER_LIST()}return {constants,registry:Battle.LAYER,resources,layers:b.layers,log:b.log,modelSaves:saves,callbacks}}
fs.mkdirSync(path.dirname(process.argv[3]),{recursive:true});fs.writeFileSync(process.argv[3],JSON.stringify(Object.fromEntries(F.cases.map(c=>[c.name,run(c)]))));
