#!/usr/bin/env node
/* Actual recovered Control/Ctrl factory runner.  Helpers are only overridden
 * where a fixture explicitly isolates the branch being selected. */
const fs=require('fs'),path=require('path'),F=JSON.parse(fs.readFileSync(process.argv[2]));global.cc={_RF:{push(){},pop(){}},v2:(x,y)=>({x,y})};
const AI={BEI_DONG_CHU_JI:0,ZHU_DONG_CHU_JI:1,JIAN_SHOU_YUAN_DI:2,GONG_JI_WU_JIANG:3,DAO_ZHI_DING_DIAN:4,GEN_SUI_WU_JIANG:5,TAO_ZHI_ZHI_DING_DIAN:6,YDDZDDJS:7,YDDZDDBM:8,YDDZDDGJ:9};const bc={AI};const cfg={AI_VALUE:{GJZDWJ:71,FXMBDZ:83},HITAREA:{MO_YU_JIAN3:1,QUN_XIONG:2},HITAREA_ATTR_NAME:{PS:0},CFG_TERRAIN_ATTR_NAME:{RESUMEHP:0},BATTLE_CAMP:{MINE:1},ARM_TYPE:{WEN_GUAN:99}};
function factory(name,deps){let e={};require(path.resolve(__dirname,'../../jojo_mobile/sgccz-desktop/recovered-js/modules/battle/'+name+'.js'))(n=>deps[n]||{}, {}, e);return e}
const model={default:{instance:()=>({hitareaAttr:(id)=>id===1?[[1,0],[-1,0]]:[[1,0]],cfgTerrainAttr:(id)=>id===5?9:id===6?3:0})}};const Control=factory('Control',{Config:cfg,Instance:{default:{instance:()=>({})}},Model:model,BattleConfg:bc}).Control;const JS=factory('CtrlYDDZDDJS',{Control:{Control}}).CtrlYDDZDDJS;const classes={CtrlDZDD:factory('CtrlDZDD',{Control:{Control},BattleConfg:bc}).CtrlDZDD,CtrlGJWJ:factory('CtrlGJWJ',{Control:{Control},Config:cfg,BattleConfg:bc}).CtrlGJWJ,CtrlGSWJ:factory('CtrlGSWJ',{Control:{Control},BattleConfg:bc}).CtrlGSWJ,CtrlTZZDD:factory('CtrlTZZDD',{Control:{Control},Config:cfg,BattleConfg:bc}).CtrlTZZDD,CtrlYDDZDDBM:factory('CtrlYDDZDDBM',{Control:{Control}}).CtrlYDDZDDBM,CtrlYDDZDDGJ:factory('CtrlYDDZDDGJ',{CtrlYDDZDDJS:{CtrlYDDZDDJS:JS},Config:cfg}).CtrlYDDZDDGJ};
function unit(x=1,y=1){return{x:()=>x,y:()=>y,pos:()=>({x,y}),setAI:v=>uLog.push('setAI:'+v),isMaBi:()=>false,isCanXue:()=>false,isMine:()=>false,index:()=>10,type:()=>0}}let uLog=[];
function env(){uLog=[];const controls=[],results=[];const u=unit();const battle={unit:()=>null,searchUnitByPos:()=>null,AStar:()=>null,findEmptyPos:()=>null,getBattleTerrain:(x,y)=>x===2?5:6,unitIter:()=>{}};const m={unit:()=>u,battle:()=>battle,psAry:()=>[{x:1,y:1},{x:2,y:1}],psHash:()=>({'257':1,'513':1}),setControl:(...a)=>controls.push(a),setResult:v=>results.push(v)};return{u,battle,m,controls,results}}
function snap(ret,e,extra={}){return{ret,unitEvents:[...uLog],controls:e.controls,results:e.results,...extra}}
function run(c){let e=env(),x,target;switch(c.kind){
case'dzdd_arrival':x=new classes.CtrlDZDD;x.setManager(e.m);x.setWithData(-1,1,1);x._cxpl=()=>0;x._zdmdd=()=>0;x._ganlu=()=>0;return snap(x._selectMovePoint2(),e);
case'gjwj_missing':x=new classes.CtrlGJWJ;x.setManager(e.m);x._cxpl=()=>0;x.getUnitByTargetUnit=()=>null;return snap(x._selectMovePoint2(),e);
case'gjwj_friend_near':x=new classes.CtrlGJWJ;x.setManager(e.m);x._cxpl=()=>0;x.getUnitByTargetUnit=()=>({isExist:()=>true,isMine:()=>false,distance:()=>2});return snap(x._selectMovePoint2(),e);
case'gjwj_enemy_attack':x=new classes.CtrlGJWJ;x.setManager(e.m);x._cxpl=()=>0;target={isExist:()=>true,isMine:()=>true,index:()=>4,x:()=>8,y:()=>9};x.getUnitByTargetUnit=()=>target;x._aiHaveAttackTargets=()=>true;return snap(x._selectMovePoint2(),e,{target:[x._targetX,x._targetY]});
case'gswj':x=new classes.CtrlGSWJ;x.setManager(e.m);x._cxpl=()=>0;target={isExist:()=>true,distance:()=>4,x:()=>8,y:()=>9};x.getUnitByTargetUnit=()=>target;x._ganlu=f=>{uLog.push('ganlu:'+f);return 1};return snap(x._selectMovePoint2(),e,{target:[x._targetX,x._targetY]});
case'tzzdd':x=new classes.CtrlTZZDD;x.setManager(e.m);x.setWithData(-1,1,1);x._zdmdd=()=>0;x._ganlu=()=>0;return snap(x._selectMovePoint2(),e,{score:x._AIProcess1()});
case'yddbm':x=new classes.CtrlYDDZDDBM;x.setManager(e.m);x.setWithData(-1,7,8);const ps=[];x._psAryIter(p=>ps.push([p.x,p.y]));const old=Control.prototype._AIProcess;Control.prototype._AIProcess=function(v){uLog.push('baseAI:'+v)};x._AIProcess();Control.prototype._AIProcess=old;return snap(null,e,{points:ps});
case'yddgj':x=new classes.CtrlYDDZDDGJ;x.setManager(e.m);x.getUnitByTargetUnit=()=>({index:()=>4});return snap(null,e,{scores:[x._AIProcess2({index:()=>4}),x._AIProcess2({index:()=>5})]});
case'process1':x=new Control;x.setManager(e.m);e.u.isMaBi=()=>true;const procA=x._process1();e.u.isMaBi=()=>false;x._isBBW=()=>true;const procB=x._process1();return snap([procA,procB],e);
case'cxpl_resume':x=new Control;x.setManager(e.m);e.u.isCanXue=()=>true;x._findCanResumeTerrainPoint=()=>({x:5,y:6});return snap(x._cxpl(),e);
case'ps_iter':x=new Control;x.setManager(e.m);const visited=[];x._psAryIter(p=>{visited.push([p.x,p.y]);return true});return snap(null,e,{visited});
case'ai_empty':x=new Control;x.setManager(e.m);Object.assign(e.u,{skill:()=>255,isCanXue:()=>false,pos:()=>({x:1,y:1}),isMine:()=>false,unit:()=>({armType:()=>0,isRemoteArm:()=>false}),terrainImpact:()=>0,hitareaIdx:()=>1,effarea:()=>0,magics:()=>[],isFengZhou:()=>false,mp_cur:()=>1});e.battle.fastSetUnitPos=()=>{};e.battle.filterHitAreaUnit=()=>[];x._AIProcess();return snap(null,e);
case'zdmdd':x=new Control;x.setManager(e.m);x.setWithData(-1,1,1);const zA=x._zdmdd(1);const zB=x._zdmdd(0);e.battle.searchUnitByPos=()=>({});const zC=x._zdmdd(0);return snap([zA,zB,zC],e);
case'ganlu':x=new Control;x.setManager(e.m);x.setWithData(4,8,9);x._AStar=()=>({x:3,y:4});const gA=[x._ganlu(0),x._ganlu(1),x._ganlu(2)];x._AStar=()=>null;e.battle.AStar=()=>[{x:2,y:2}];e.battle.searchUnitByPos=()=>({isMine:()=>true,index:()=>99});const gB=x._ganlu(0);e.battle.AStar=()=>null;const gD=x._ganlu(0);return snap([gA,gB,gD],e);
case'search_resume':x=new Control;x.setManager(e.m);const near1={isExist:()=>true,isMine:()=>true,index:()=>3,pos:()=>({x:3,y:1})},near2={isExist:()=>true,isMine:()=>true,index:()=>2,pos:()=>({x:2,y:1})};e.battle.unitIter=f=>{f(near1);f(near2)};e.battle.AStar=()=>[{x:0,y:0},{x:1,y:1}];const near=x._searchNearUnit(0);e.m.psAry=()=>[{x:1,y:1},{x:2,y:1},{x:3,y:1}];e.battle.searchUnitByPos=(x)=>x===2?{index:()=>99}:null;const resume=x._findCanResumeTerrainPoint(1);return snap(null,e,{near,resume:resume&&[resume.x,resume.y]});
}}
fs.mkdirSync(path.dirname(process.argv[3]),{recursive:true});fs.writeFileSync(process.argv[3],JSON.stringify(Object.fromEntries(F.cases.map(c=>[c.name,run(c)]))));
