#!/usr/bin/env node
/* Recovered-factory trace runner: Feats/JiQi/Attribute/Exclusive. */
const fs=require('fs'),path=require('path'),fixture=JSON.parse(fs.readFileSync(process.argv[2]));
function N(){this.children=[];this.active=true;this.tag2=0;this._c=new Map();this._labels={};this._parent=null}Object.defineProperty(N.prototype,'parent',{get(){return this._parent},set(v){this._parent=v;if(v&&!v.children.includes(this))v.children.push(this)}})
function Label(){this.node=new N;this._string=''}Object.defineProperty(Label.prototype,'string',{get(){return this._string},set(v){this._string=String(v);if(global.current)global.current._labelValues[this._key]=this._string}})
function Button(){this.node=new N;this.interactable=true} function Bar(){this.node=new N;this.progress=0} function Sprite(){this.node=new N}
function Pool(){this.a=[]}Pool.prototype={put(x){this.a.push(x)},get(){return this.a.pop()||new N},size(){return this.a.length},clear(){this.a=[]}}
function Base(){this.n={};this.layers=[];this.dead=false;this.events=[];this.m_manager={itemDir:x=>'i/'+x};this._labelValues={}}Base.prototype._setBg=function(){};Base.prototype.onDestroy=function(){};Base.prototype.seekNodeByName=function(k,p){let x=p||this;if(!x.n)x.n={};return x.n[k]||(x.n[k]=new N)};Base.prototype.seekCompByName=function(K,k,p){let target=this.seekNodeByName(k,p);let q=K.name||'component';if(!target._c.has(q)){let z=new K;z.node=target;z._key=k;target._c.set(q,z)}return target._c.get(q)};Base.prototype.addTouchEventListener=function(n,h){(n.node||n).listener=h};Base.prototype.addLayer=function(l,a){this.layers.push({layer:l,args:a||null})};Base.prototype.removeFromParent=function(){this.dead=true};Base.prototype.loadByUrl=function(f){f({ret:'s'})};Base.prototype.fastInitList=function(xs,n,f){xs.forEach(f)};
global.cc={_RF:{push(){},pop(){}},_decorator:{ccclass:x=>x,property:()=>()=>{}},Component:Base,Label,Button,ProgressBar:Bar,Sprite,SpriteFrame:class{},NodePool:Pool,instantiate:()=>new N,color:(...x)=>x};
const C={UNIT_ATTR_NAME2:{WL:0,TS:1,ZL:2,MJ:3,YQ:4},TIANFU_MAX_COUNT:2,UNIT_TIANFU_TZ:{ITEM0:0,ITEM1:1,ITEM2:2,EFF_VALUE:3,INTRO:4},UNIT_TIANFU_ZS:{UNIT_ID:0,ITEM_ID:1,EFF_VALUE:2,INTRO:3},DEFAULT_SKILL_ITEM_ID:255,DEFAULT_SKILL_EFFVAL:0,DEFAULT_SKILL_INTRO:'',DEFAULT_SKILL_UNIT_ID:1024,ITEM_ATTR_NAME:{NAME:0},ITEM_ATTR_NAME2:{ICON:0}};
let data; const Model={default:{instance:()=>({getTZSKill:(i,j,k,d)=>((data.tz||[])[i*2+j]||[])[k]??d,getZSSkill:(i,j,k,d)=>((data.zs||[])[i*2+j]||[])[k]??d,itemAttr:i=>'Item'+i,itemAttr2:i=>i})}};const Unit={default:{unitName:i=>'U'+i}};const Instance={default:{LAYER:{MsgBox:'MsgBox'}}};
function load(n){let e={};require(path.resolve(__dirname,'../../jojo_mobile/sgccz-desktop/recovered-js/modules/ui/'+n+'.js'))(x=>({UILayer:{default:Base},Config:C,Instance,Model,Unit,InfoBaseLayer:{default:Base}}[x]||{}),{},e);return e.default}const Feats=load('FeatsLayer'),JiQi=load('JiQiLayer'),Attribute=load('AttributeLayer'),Exclusive=load('ExclusiveLayer');
function labels(l){return Object.entries(l._labelValues).sort((x,y)=>x[0].localeCompare(y[0]))}function snap(l,kind,step){let x={step,dead:l.dead,labels:labels(l),layers:l.layers.map(z=>z.layer)};if(kind==='exclusive'){x.sel=l._sel??null;x.flag=l._flag??0;x.panels=(l._panel||[]).map(n=>n.active);x.buttons=(l._btns||[]).map(b=>b.interactable);x.rows=(l._contents||[]).map(n=>n.children.length)}return x}
function unit(c){return{wuwei:i=>c.wuwei[i],featsAttrByName:i=>c.feats[i][0],nextFeats:i=>c.feats[i][1],nextAbilityPhase:i=>c.feats[i][2]}}
function run(c){data=c;let l;if(c.kind==='feats') {l=new Feats}else if(c.kind==='jiqi'){l=new JiQi}else if(c.kind==='attribute'){l=new Attribute}else l=new Exclusive;global.current=l;if(c.kind==='feats') l.onCreate(unit(c));else if(c.kind==='jiqi')l.onCreate({rates:()=>c.rates});else if(c.kind==='attribute')l.onCreate(c.rows);else l.onCreate();let out=[snap(l,c.kind,'create')];for(const e of c.events){let p=e.split(':');if(p[0]==='button'){let n=l.seekNodeByName('Logo_12-1/button'+p[1]);n.tag2=+p[1];n.listener(n,+p[2])}else if(p[0]==='cancel'){let n=l.seekNodeByName('Panel_cancel');n.listener(n,+p[1])}else if(p[0]==='tab'){let b=l._btns[+p[1]];if(!b.node.listener)throw Error('no listener '+p[1]);b.node.listener(b,+p[2])}out.push(snap(l,c.kind,e))}return out}fs.mkdirSync(path.dirname(process.argv[3]),{recursive:true});fs.writeFileSync(process.argv[3],JSON.stringify(Object.fromEntries(fixture.cases.map(c=>[c.name,run(c)]))));
