#!/usr/bin/env node
/* Executes recovered choice/command factories with only their used Cocos APIs. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const fixture=JSON.parse(fs.readFileSync(process.argv[2],'utf8')), output=process.argv[3]; let currentModel={replaceSpeInfo:s=>s}, nextId=0;
function Node(name='node'){this.name=name;this.id=++nextId;this.active=true;this.tag2=0;this.parent=null;this.width=0;this.height=0}
function Text(){this.node=new Node('text');this.string=''} function Button(){this.node=new Node('button');this.interactable=true}
function Sprite(){this.node=new Node('sprite');this.spriteFrame=null;this.materials=[];this.node.setContentSize=(w,h)=>{this.node.width=w;this.node.height=h};this.setMaterial=(slot,v)=>this.materials[slot]=v}
function Frame(){this.getOriginalSize=()=>({width:60,height:120})}
function Base(){this.node=new Node('root');this.nodes={};this.comps={};this.listeners=[];this.removed=0;this.loadRequests=[]}
Base.prototype.seekNodeByName=function(name,parent){const key=(parent?parent.id:'root')+'/'+name;if(!this.nodes[key]){const n=new Node(name);if(name.endsWith('/item'))n.parent=new Node('content');this.nodes[key]=n}return this.nodes[key]};
Base.prototype.seekCompByName=function(K,name,parent){const key=(parent?parent.id:'root')+'/'+name;if(!this.comps[key]){const c=new K();if(parent)c.node=parent;this.comps[key]=c}return this.comps[key]};
Base.prototype.addTouchEventListener=function(target,fn,priority){target.listener=fn;target.priority=priority;this.listeners.push(target)}; Base.prototype.removeFromParent=function(){this.removed++}; Base.prototype._setBg=function(){}; Base.prototype._setpos=function(){};Base.prototype.headDir=face=>'head/'+face;Base.prototype.loadByUrl=function(fn,url,K){this.loadRequests.push([url,K===Frame?'SpriteFrame':'?']);fn({err:false,ret:new Frame()})};
global.cc={_RF:{push(){},pop(){}},_decorator:{ccclass:x=>x,property:()=>()=>{}},RichText:Text,Label:Text,Button,Sprite,SpriteFrame:Frame,Material:class{},instantiate:n=>{const c=new Node(n.name);c.parent=n.parent;return c},color:x=>x};
function load(kind){const file={choose:'ChooseLayer.js',choose2:'Choose2Layer.js',command:'CommandLayer.js'}[kind],exported={};require(path.resolve(__dirname,'../../jojo_mobile/sgccz-desktop/recovered-js/modules/ui/'+file))(name=>{if(name==='UILayer'||name==='InfoBaseLayer')return{default:Base};if(name==='Config')return{Z_INDEX:{CHOICE_LAYER:100}};if(name==='Model')return{default:{instance:()=>currentModel}};return{default:{}}},{},exported);assert.ok(exported.default);return exported.default}
function replace(s,table){for(const [a,b] of Object.entries(table||{}))s=s.split(a).join(b);return s}
function run(spec){currentModel={replaceSpeInfo:s=>replace(s,spec.replace)};const Source=load(spec.kind),layer=new Source(),calls=[];const arg=spec.kind==='command'?{c:{node:new Node('anchor')},flag:spec.mask,func:i=>calls.push(i)}:{info:spec.info,face:spec.face,fn:i=>calls.push(i)};layer.onCreate(arg);
 const snap=step=>{const rows=spec.kind==='command'?Array.from({length:7},(_,i)=>{const b=layer.seekCompByName(Button,'bg/button'+i);return[i,b.interactable,b.priority,i<5&&!b.interactable]}):layer.listeners.map(n=>[n.tag2,spec.kind==='choose'?layer.seekCompByName(Text,'bg6/richtext',n).string:layer.seekCompByName(Text,'bg6/Label',n).string,n.priority]);const face=spec.kind==='choose'?(()=>{const s=layer.seekCompByName(Sprite,'bg/face');return{request:layer.loadRequests.map(x=>x[0]),size:[s.node.width,s.node.height]}})():null;const cancel=spec.kind==='command'?layer.seekNodeByName('Panel_cancel'):null;return{step,zIndex:layer.node.zIndex??0,rows,face,attached:layer.removed===0,removeCount:layer.removed,calls:[...calls],cancelPriority:cancel?.priority??null,keyboardBindings:0}};
 const trace=[snap('create')];for(const event of spec.events){const [type,tag,no]=event.split(':');if(type==='row'){const target=layer.listeners.find(x=>x.tag2===+tag);assert.ok(target);target.listener(target,+no)}else if(type==='button'){const target=layer.seekCompByName(Button,'bg/button'+tag);target.listener(target,+no)}else{const target=layer.seekNodeByName('Panel_cancel');target.listener(target,+tag)}trace.push(snap(event))}return trace}
const traces=Object.fromEntries(fixture.cases.map(c=>[c.name,run(c)]));fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(traces));console.log(JSON.stringify(traces));
