#!/usr/bin/env node
/* Recovered factory execution harness for all edit owners.  It deliberately
 * invokes the original registered touch closures rather than reimplementing
 * their decisions in this driver. */
const fs=require('fs'),path=require('path');const fixture=JSON.parse(fs.readFileSync(process.argv[2]));
function Node(){this.active=true;this.tag2=0;this.children=[];this.parent={};this.fn=null;this.node=this;this.isChecked=false}Node.prototype.getComponent=function(){return this};
function Label(){this.node=new Node;this.string=''} function EditBox(){this.node=new Node;this.string=''} function Button(){this.node=new Node;this.interactable=true} function Toggle(){this.node=new Node;this.isChecked=false;this.check=()=>this.isChecked=true;this.uncheck=()=>this.isChecked=false} function ScrollView(){this.node=new Node;this.scrollToTop=()=>{}} function Sprite(){this.node=new Node}
function Pool(){this.a=[];this.put=x=>this.a.push(x);this.get=()=>this.a.pop()||new Node;this.size=()=>this.a.length;this.clear=()=>this.a=[]}
function U(){this.n={};this.c={};this.layers=[];this.toasts=[];this.dispatch=[];this.removed=false;this.m_manager={addEvent(){}};this.node=new Node}
U.prototype._setBg=function(){};U.prototype.replaceScene=function(v){this.scene=v};U.prototype.eFlag=function(){return this.flag||0};U.prototype.rFlag=function(){return this.rflag||0};U.prototype.seekNodeByName=function(n,p){let k=(p&&p._k?p._k+'/':'')+n;return this.n[k]||(this.n[k]=Object.assign(new Node,{_k:k}))};U.prototype.seekCompByName=function(K,n,p){let k=(p&&p._k?p._k+'/':'')+n;if(!this.c[k]){let x=new K;x.node._k=k;this.c[k]=x;this.n[k]=x.node}return this.c[k]};U.prototype.addTouchEventListener=function(x,f){(x.node||x).fn=f};U.prototype.addLayer=function(n,o){this.layers.push([n,o]);this.lastLayer=[n,o]};U.prototype.removeFromParent=function(){this.removed=true};U.prototype.cmdToast=function(t){this.toasts.push(t)};U.prototype.dispatchEvent=function(n,v){this.dispatch.push([n,v])};U.prototype.getLayer=function(){return this.battleLayer};U.prototype.onDestroy=function(){};
global.cc={_RF:{push(){},pop(){}},_decorator:{ccclass:x=>x,property:()=>()=>{}},Node,NodePool:Pool,Label,EditBox,Button,Toggle,ScrollView,Sprite,SpriteFrame:function(){},WrapMode:{Loop:1},instantiate:x=>new Node,director:{getScheduler:()=>({setTimeScale(){}})},loader:{load:(x,f)=>f(null,{})}};global.jsb={fileUtils:{getWritablePath:()=>'/w/',isFileExist:()=>false,getStringFromFile:()=>''}};
const C={ENABLED_FEATURE:{EDIT:1,FULLLV:2,ZJHH:4,GZZJNL:8,ZDSJ:16,YJQB:32},BATTLE_UNIT_STATUS2:{MOV:1,XD:2,MAX:3},UNIT_ATTR_NAME2:{ATT:0,MOR:4,WL:0,YQ:4},ITEM_TYPE:{WEAPONS:0,ARMOR:1,AUXILIARY:2},STAGE:{HALL_SCENE:'hall'},SHOP_ATTR_NAME:{NAME:0},UNIT_LIMIT:30};
U.LAYER={EditLayer:'EditLayer',SAvatarEditLayer:'SAvatarEditLayer',MsgBox:'MsgBox',SelectListLayer:'SelectListLayer',LearnUnitSkillLayer:'LearnUnitSkillLayer',InfoLayer:'InfoLayer'};
function load(folder,file,res){let e={};require(path.resolve(__dirname,'../../jojo_mobile/sgccz-desktop/recovered-js/modules',folder,file))(res,{},e);return e.default}
let model;
function res(n){if(n==='UILayer')return{default:U};if(n==='Config')return C;if(n==='Battle')return{default:{LAYER:{BattleLayer:'BattleLayer'}}};if(n==='BattleConfg')return{UNIT_STATUS_LIFT:{DOWN:0,NORMAL:1,UP:2}};if(n==='Instance')return{default:{LAYER:U.LAYER,range:(v,a,b)=>Math.max(a,Math.min(b,v))}};if(n==='Model')return{default:{instance:()=>model}};if(n==='Unit')return{default:{lvLimit:()=>50}};if(n==='Item')return{default:function(id){this.id=()=>id;this.type=()=>0;this.name=()=>`I${id}`;this.lv=()=>1;this.exp=()=>0}};if(n==='ItemStore')return{default:{instance:()=>({clear:()=>model.clears++})}};return{default:U}}
const Edit=load('ui','EditLayer.js',res), E2=load('misc','EditLayer2.js',res), E3=load('misc','EditLayer3.js',res), E4=load('misc','EditLayer4.js',res), Avatar=load('ui','SAvatarEditLayer.js',n=>n==='UILayer'?{default:U}:n==='Model'?{default:{instance:()=>model}}:n==='Manager'?{getManager:()=>({setGameSpeed(){}})}:n==='Config'?{default:C}:n==='Tool'?{default:{len:o=>Object.keys(o).length}}:n==='UUIDManager'?{UUIDManager:function(){this.decodeUuid=x=>x}}:n==='UIFrame'?{default:{}}:res(n));
function makeModel(){let units={};function unit(id){return units[id]||(units[id]={_id:id,id(){return id},name(){return`U${id}`},leave(){return !!this.left},posts(){return 0},postsPhase(){return 0},battle_n(){return 0},retreat_n(){return 0},arm(){return 0},baseBility(){return 1},ability(){return 1},wuwei(){return 1},hp(){return 20},mp(){return 10},lv(){return 1},exp(){return 0},equip(){return null},setLevel(v){this.level=v},setPosts(v){this.postsV=v},setAbility(v,k){this['a'+k]=v},setWuWei(k,v){this['w'+k]=v},setExp(v){this.expV=v}})};return{amb:10,cash:100,stageV:1,clears:0,avatar:null,ambition(){return this.amb},money(){return this.cash},stage(){return this.stageV},setAmbition(v){this.amb=v},setMoney(v){this.cash=v},setStage(v){this.stageV=v},shopAttr:(i)=>i===0?'Shop':'터미널',shopDataLen:()=>2,unitsIter(f){[0,7].forEach(i=>f(unit(i)))},getUnits(){return Object.values(units)},unit,unitAttr2:i=>`U${i}`,unitJoin(i,a){let u=unit(i);u.left=a===255},setUnitSavatar(i,v){this.avatar=[i,v]},postsAttr:()=> 'P',postsIter(){},itemIter(){}}}
function fire(n,ev=2){n=n.node||n;if(!n.fn)throw Error('no listener '+n._k);n.fn(n,ev)} function snap(step,x,extra={}){return{step,attached:!x.removed,layers:x.layers.map(x=>x[0]),toasts:[...x.toasts],dispatch:x.dispatch.map(v=>[...v]),...extra}}
function battle(c){model=makeModel();let x=new E2;x.flag=c.flag;x.rflag=c.flag;x.battleLayer={weather:()=>0,getRound:()=>10,setWeather:v=>x.weather=v,setRound:v=>x.round=v};x.onCreate();let out=[snap('create',x,{weather:0,round:10})];for(const s of c.events){let p=s.split(':');if(p[0]==='weather'){x._data2['0']=+p[1]}else if(p[0]==='round'){x._data2['1']=+p[1]}else if(p[0]==='apply')fire(x.seekNodeByName('bg/button0'),+p[1]);else if(p[0]==='kill')fire(x.seekNodeByName('bg/button'+p[1]),+p[2]);out.push(snap(s,x,{weather:x.weather??0,round:x.round??10}))}return out}
function unitCase(c){model=makeModel();let u=model.unit(1),b={unit:()=>u,pos:()=>({x:1,y:1}),status:()=>1,setStateRound(){},refStateAnime(){},setPos(){},setCurHp(){},setCurMp(){},setAI(){},loadAvatar(){},defaultAction(){}};let x=new Edit;x.flag=c.flag;x.rflag=c.flag;x._battleUnit=b;x._unit=u;x._data2={14:99};try{x.onCreate({battleUnit:b})}catch(_){}let out=[snap('create',x,{level:u.level||1})];for(const s of c.events){let p=s.split(':');if(p[0]==='level')x._data2['14']=+p[1];if(p[0]==='apply'){let n=x.seekNodeByName('bg/button0');fire(n,+p[1])}out.push(snap(s,x,{level:u.level||1}))}return out}
function globalCase(c){model=makeModel();let x=new E3;x.flag=c.flag;x.item=new Node;x.item.parent=new Node;x.onCreate();let out=[snap('create',x,{ambition:model.amb,money:model.cash,stage:model.stageV,clears:model.clears})];for(const s of c.events){let p=s.split(':');if(p[0]==='ambition')x._data2['1']=+p[1];else if(p[0]==='money')x._data2['2']=+p[1];else if(p[0]==='stage')x._data2['0']=+p[1];else if(p[0]==='apply')fire(x.seekNodeByName('bg/button0'),+p[1]);else if(p[0]==='store')fire(x.seekNodeByName('bg/button2'),+p[2]);else if(p[0]==='confirm'&&x.lastLayer?.[1]?.fn)x.lastLayer[1].fn(+p[1]);out.push(snap(s,x,{ambition:model.amb,money:model.cash,stage:model.stageV,clears:model.clears}))}return out}
function roster(c){model=makeModel();let x=new E4;x.flag=c.flag;x.item=new Node;x.onCreate();let out=[snap('create',x,{joined:model.getUnits().filter(u=>!u.leave()).map(u=>u.id())})];for(const s of c.events){let p=s.split(':');if(p[0]==='edit'||p[0]==='all'||p[0]==='learn'||p[0]==='close')fire(x.seekCompByName(Button,'bg/button'+p[1]),+p[2]);else if(p[0]==='select'){x.lastLayer[1].func(+p[1])}else if(p[0]==='leave'){x.onClick({tag2:1},+p[2])}else if(p[0]==='confirm')x.lastLayer[1].fn(+p[1]);out.push(snap(s,x,{joined:model.getUnits().filter(u=>!u.leave()).map(u=>u.id())}))}return out}
function avatar(c){model=makeModel();let b={loadAvatar(){this.loads=(this.loads||0)+1},unit:()=>model.unit(1)};let x=new Avatar;x._refGameList=()=>1;x.onCreate({battleUnit:b});x._appids=['12'];x._choiceMod=0;x._choiceAvatar=5;let out=[snap('create',x,{avatar:model.avatar,loads:b.loads||0,page:x._curPage})];for(const s of c.events){let p=s.split(':');if(p[0]==='apply'||p[0]==='reset'||p[0]==='prev'||p[0]==='next')fire(x.seekNodeByName('Logo_12-1/button'+(p[0]==='apply'?0:p[0]==='reset'?4:p[0]==='prev'?2:3)),+p[p.length-1]);out.push(snap(s,x,{avatar:model.avatar,loads:b.loads||0,page:x._curPage}))}return out}
function run(c){return c.owner==='battle'?battle(c):c.owner==='unit'?unitCase(c):c.owner==='global'?globalCase(c):c.owner==='roster'?roster(c):avatar(c)}const out=Object.fromEntries(fixture.cases.map(c=>[c.id,run(c)]));fs.mkdirSync(path.dirname(process.argv[3]),{recursive:true});fs.writeFileSync(process.argv[3],JSON.stringify(out));
