#!/usr/bin/env node
/* Recovered factory harness: WinConBoxLayer, Lose, End and SkipLayer. */
const fs=require('node:fs'),path=require('node:path');const fixture=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
function Node(name){this.name=name;this.active=true;this.zIndex=0} function Label(){this.string=''} function Scroll(){this.top=0;this.scrollToTop=()=>this.top++} function Button(){this.node=new Node('button')}
function UILayer(){this.node=new Node('root');this.nodes={};this.comps={};this.backgrounds=[];this.removed=0;this.layers=[];this.dispatches=[]}
UILayer.prototype._setBg=function(x){this.backgrounds.push(x)};UILayer.prototype.seekNodeByName=function(n){return this.nodes[n]||(this.nodes[n]=new Node(n))};UILayer.prototype.seekCompByName=function(K,n){return this.comps[n]||(this.comps[n]=new K())};UILayer.prototype.addTouchEventListener=function(n,f,p){n.listener=f;n.priority=p};UILayer.prototype.removeFromParent=function(){this.removed++};UILayer.prototype.addLayer=function(k,d){this.layers.push([k,d]);this.pending=d};UILayer.prototype.dispatchEvent=function(x){this.dispatches.push(x)};
function UIScene(){UILayer.call(this);this.sounds=[];this.scheduled=[];this.helpers=[];this.scenes=[];this.cmds=[]} UIScene.prototype=Object.create(UILayer.prototype);UIScene.prototype.constructor=UIScene;UIScene.prototype.playSoundEffect=function(x){this.sounds.push(x)};UIScene.prototype.scheduleOnce=function(f,n){this.scheduled.push([n,f])};UIScene.prototype.replaceScene=function(x){this.scenes.push(x)};UIScene.prototype.addCmd=function(x){this.cmds.push(x)};
global.cc={_RF:{push(){},pop(){}},_decorator:{ccclass:x=>x,property:()=>()=>{}},ScrollView:Scroll,Button:Button,Label:Label};
function load(rel,deps,Base){const ex={};require(path.resolve(__dirname,'../../jojo_mobile/sgccz-desktop/recovered-js/modules/'+rel))(n=>deps[n]||{default:{}},{},ex);return ex.default}
const W=load('battle/WinConBoxLayer.js',{UILayer:{default:UILayer}},UILayer); const L=load('battle/Lose.js',{EngineCfg:{CMDS:{END_GAME:'END_GAME'}},Manager:{default:{helper(x){global.__helpers.push(x)}}},UIScene:{default:UIScene},Config:{SOUND_INDEX:{LOSE:'LOSE'},STAGE:{LOGIN_SCENE:'LOGIN'}},Instance:{default:{LAYER:{MsgBox:'MsgBox'}}}},UIScene); const E=load('ui/End.js',{UIScene:{default:UIScene},Config:{STAGE:{LOGIN_SCENE:'LOGIN'}}},UIScene);const S=load('ui/SkipLayer.js',{UILayer:{default:UILayer},Config:{Z_INDEX:{SKIP_LAYER:999}},Instance:{default:{LAYER:{MsgBox:'MsgBox'}}}},UILayer);
function run(c){global.__helpers=[];let x,cb=0; if(c.kind==='wincon'){x=new W();x.lab=new Label();x.onCreate({info:c.info,func:()=>cb++})}else if(c.kind==='lose'){x=new L();x.onCreate()}else if(c.kind==='end'){x=new E();x.onCreate()}else{x=new S();x.onCreate()} const snap=(step)=>({step,kind:c.kind,backgrounds:[...(x.backgrounds||[])],label:x.lab?.string||'',scrollTop:x.comps?.['bg0/scrollview']?.top||0,attached:(x.removed||0)===0,removed:x.removed||0,callbacks:cb,panel:x._panel?.active??null,button:x._skipBtn?.node.active??null,z:x.node.zIndex||0,sounds:[...(x.sounds||[])],scheduled:(x.scheduled||[]).map(v=>v[0]),helpers:[...global.__helpers],layers:(x.layers||[]).map(v=>v[0]),dispatches:[...(x.dispatches||[])],scenes:[...(x.scenes||[])],cmds:[...(x.cmds||[])]}); const out=[snap('create')];for(const ev of c.events){let[a,b]=ev.split(':');if(a==='button'){const n=c.kind==='wincon'?x.seekNodeByName('bg0/button'):x._skipBtn; n.listener({node:n.node||n},+b)}if(a==='time'){for(const [n,f] of x.scheduled||[])if(n<=+b)f(); x.scheduled=(x.scheduled||[]).filter(([n])=>n>+b)}if(a==='msg')x.pending?.fn(+b);if(a==='event')x.onEvent(null,+b);if(a==='swap')x.swap();out.push(snap(ev))}return out}
const o=Object.fromEntries(fixture.cases.map(c=>[c.name,run(c)]));fs.mkdirSync(path.dirname(process.argv[3]),{recursive:true});fs.writeFileSync(process.argv[3],JSON.stringify(o));console.log(JSON.stringify(o));
