#!/usr/bin/env node
'use strict';

// Controlled source-engine fixture: call the shipped HallUnit._move2 and step
// the cc.Sequence it creates with explicit deltas. This is not a natural run.
const {spawn,spawnSync}=require('node:child_process');
const crypto=require('node:crypto');
const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');

const sourceRoot=path.resolve(process.env.JOJO_SOURCE_ROOT||path.join(__dirname,'../../jojo_mobile/sgccz-desktop'));
const outputRoot=path.resolve(process.argv[2]||path.join(process.cwd(),'build/reports/opening-hall-precision-source'));
const port=Number(process.env.JOJO_CDP_PORT||9820+process.pid%70),deadlineMs=Number(process.env.JOJO_EXPORT_DEADLINE_MS||15000);
if(!Number.isFinite(port)||!Number.isFinite(deadlineMs)||deadlineMs<1000||deadlineMs>15000)throw Error('deadline must be 1000..15000ms and port numeric');
fs.mkdirSync(outputRoot,{recursive:true});
const pathOracleFile=path.join(outputRoot,'.opening-paths.json');
const pathOracleTool=path.join(__dirname,'r00_opening_source_move_harness.js');
const pathOracleRun=spawnSync(process.execPath,[pathOracleTool,pathOracleFile],{encoding:'utf8',timeout:10000,env:{...process.env,JOJO_SOURCE_ROOT:sourceRoot}});
if(pathOracleRun.status!==0)throw Error(`opening path oracle failed: ${pathOracleRun.stderr||pathOracleRun.stdout}`);
const pathOracle=JSON.parse(fs.readFileSync(pathOracleFile));fs.rmSync(pathOracleFile);
const sourcePaths={singleton:[[40,5]],straight:pathOracle.groups[0].actors[0].path,turn:pathOracle.groups[2].actors.find(x=>x.id===0)?.path};
if(sourcePaths.straight.length!==11||sourcePaths.turn?.length!==23)throw Error('unexpected R_00 opening paths');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const shaFile=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const getJson=url=>new Promise((resolve,reject)=>{const q=http.get(url,r=>{let b='';r.on('data',x=>b+=x);r.on('end',()=>{try{resolve(JSON.parse(b))}catch(e){reject(e)}})});q.setTimeout(1000,()=>q.destroy(Error('CDP HTTP timeout')));q.on('error',reject)});
async function poll(fn,label,end){let last;while(Date.now()<end){try{const x=await fn();if(x)return x}catch(e){if(e.fatal)throw e;last=e}await delay(20)}throw Error(`timeout waiting for ${label}: ${last||''}`)}
async function connect(url){const s=new WebSocket(url);await new Promise((r,j)=>{s.addEventListener('open',r,{once:true});s.addEventListener('error',j,{once:true})});let id=0;const waits=new Map();s.addEventListener('message',e=>{const m=JSON.parse(e.data),w=waits.get(m.id);if(w){waits.delete(m.id);m.error?w.reject(Error(JSON.stringify(m.error))):w.resolve(m.result)}});s.addEventListener('close',()=>{const e=Error('CDP closed before fixture completed');e.fatal=true;for(const w of waits.values())w.reject(e)});return{send(method,params={}){return new Promise((resolve,reject)=>{const n=++id;waits.set(n,{resolve,reject});s.send(JSON.stringify({id:n,method,params}))})},close(){s.close()}}}
const ready=`(()=>!!(globalThis.cc&&cc.director&&cc.js&&cc.js.getClassByName('HallUnit')))()`;
const probe=`(()=>{
 const HallUnit=cc.js.getClassByName('HallUnit');if(!HallUnit||typeof HallUnit.prototype._move2!=='function')throw Error('production HallUnit._move2 unavailable');
 const epsilon=cc.macro.FLT_EPSILON,jsNumberEpsilon=Number.EPSILON,floatPointFour=Math.fround(.4),singleton=${JSON.stringify(sourcePaths.singleton)},straight=${JSON.stringify(sourcePaths.straight)};
 const turn=${JSON.stringify(sourcePaths.turn)};
 const schedules={before_0_4:{inputKind:'JavaScript double',deltas:[0,.4-epsilon]},exact_0_4:{inputKind:'JavaScript double',deltas:[0,.4]},after_0_4:{inputKind:'JavaScript double',deltas:[0,.4+epsilon]},float_0_4:{inputKind:'Math.fround then JavaScript number',deltas:[0,floatPointFour]},float_0_4_then_epsilon:{inputKind:'Math.fround every delta',deltas:[Math.fround(0),floatPointFour,Math.fround(epsilon)]},split_0_4:{inputKind:'JavaScript double split',deltas:[0,.2,.2]},split_boundary_before:{inputKind:'JavaScript double',deltas:[0,.36-epsilon]},split_boundary_exact:{inputKind:'JavaScript double',deltas:[0,.36]},split_boundary_after:{inputKind:'JavaScript double',deltas:[0,.36+epsilon]},turn_before_0_4:{inputKind:'JavaScript double cumulative',deltas:[0,.4-epsilon]},turn_exact_0_4:{inputKind:'JavaScript double cumulative',deltas:[0,.4]},turn_after_0_4:{inputKind:'JavaScript double cumulative',deltas:[0,.4+epsilon]},turn_before_0_84:{inputKind:'JavaScript double cumulative',deltas:[0,.84-epsilon]},turn_exact_0_84:{inputKind:'JavaScript double cumulative',deltas:[0,.84]},turn_after_0_84:{inputKind:'JavaScript double cumulative',deltas:[0,.84+epsilon]},turn_before_0_88:{inputKind:'JavaScript double cumulative',deltas:[0,.88-epsilon]},turn_exact_0_88:{inputKind:'JavaScript double cumulative',deltas:[0,.88]},turn_after_0_88:{inputKind:'JavaScript double cumulative',deltas:[0,.88+epsilon]},turn_segmented_double:{inputKind:'JavaScript double directional segments',deltas:[0,.36,.04,.44,.04]},turn_segmented_float:{inputKind:'Math.fround every delta',deltas:[Math.fround(0),Math.fround(.36),Math.fround(.04),Math.fround(.44),Math.fround(.04)]},singleton_double_small_steps:{inputKind:'JavaScript double small steps',deltas:[0,0,epsilon/2,epsilon/2]},singleton_float_small_steps:{inputKind:'Math.fround every delta',deltas:[Math.fround(0),Math.fround(0),Math.fround(epsilon/2),Math.fround(epsilon/2)]}};
 const run=(name,path,scheduleName,schedule)=>{const deltas=schedule.deltas;if(schedule.inputKind==='Math.fround every delta'&&deltas.some(dt=>dt!==Math.fround(dt)))throw Error('non-f32 delta in '+scheduleName);const node=new cc.Node('controlled-hall-unit'),unit=Object.create(HallUnit.prototype),actions=[];node.setPosition(path[0][0],path[0][1]);node.runAction=a=>(actions.push(a),a);unit.node=node;unit._x=path[0][0];unit._y=path[0][1];unit._hallLayer={turnPos:(x,y)=>cc.v2(x,y)};unit._anime={schedule(){},unschedule(){}};unit._moveDuring=HallUnit.prototype._moveDuring;unit.setAction=(action,direction,forced)=>callbacks.push({kind:'setAction',action,direction,forced:!!forced,stepIndex});let completeCount=0,stepIndex=-1,callbacks=[];HallUnit.prototype._move2.call(unit,path.map(p=>cc.v2(p[0],p[1])),()=>{completeCount++;callbacks.push({kind:'complete',stepIndex})});if(actions.length!==1)throw Error('expected exactly one generated action');const action=actions[0],rows=[];action.startWithTarget(node);for(stepIndex=0;stepIndex<deltas.length;stepIndex++){const dt=deltas[stepIndex];action.step(dt);rows.push({index:stepIndex,dt,position:[node.x,node.y],logical:[unit._x,unit._y],isDone:action.isDone(),callbackDirection:callbacks.filter(x=>x.kind==='setAction').at(-1)?.direction??null,completionCount:completeCount,callbacks:callbacks.filter(x=>x.stepIndex===stepIndex)})}const stoppedAfterDone=action.isDone();if(stoppedAfterDone)action.stop();return{name,path,schedule:scheduleName,inputKind:schedule.inputKind,actionDuration:action._duration,stoppedAfterDone,deltas,steps:rows,callbackDirections:callbacks.filter(x=>x.kind==='setAction').map(x=>x.direction),completionCount:completeCount}};
 const cases=[];for(const k of ['singleton_double_small_steps','singleton_float_small_steps'])cases.push(run('singleton',${JSON.stringify([[40,5]])},k,schedules[k]));for(const k of ['before_0_4','exact_0_4','after_0_4','float_0_4','float_0_4_then_epsilon','split_0_4'])cases.push(run('straight',straight,k,schedules[k]));for(const k of ['split_boundary_before','split_boundary_exact','split_boundary_after','turn_before_0_4','turn_exact_0_4','turn_after_0_4','turn_before_0_84','turn_exact_0_84','turn_after_0_84','turn_before_0_88','turn_exact_0_88','turn_after_0_88','turn_segmented_double','turn_segmented_float'])cases.push(run('turn',turn,k,schedules[k]));
 return {engineVersion:cc.ENGINE_VERSION||null,sourceFloatEpsilon:epsilon,javaScriptNumberEpsilon:jsNumberEpsilon,floatPointFour,coordinateFixture:{kind:'identity-turnPos',note:'grid coordinates are used as source node coordinates solely to isolate ActionInterval stepping'},paths:{singleton,straight,turn},cases};
})()`;

(async()=>{const expires=Date.now()+deadlineMs,startedAt=new Date();try{await getJson(`http://127.0.0.1:${port}/json/list`);throw Error(`CDP port ${port} busy`)}catch(e){if(e.code!=='ECONNREFUSED')throw e}const log=fs.openSync(path.join(outputRoot,'source-process.log'),'w'),child=spawn('npm',['exec','--','electron',path.join(__dirname,'hold_source_verification_exit.cjs'),'--verify-desktop',`--remote-debugging-port=${port}`],{cwd:sourceRoot,env:{...process.env,JOJO_SOURCE_MAIN:path.join(sourceRoot,'electron/main.cjs')},stdio:['ignore',log,log],detached:true});let client,childExit=null;child.once('exit',(code,signal)=>childExit={code,signal});const timer=setTimeout(()=>{try{process.kill(-child.pid,'SIGTERM')}catch{}setTimeout(()=>{try{process.kill(-child.pid,'SIGKILL')}catch{}process.exit(124)},250)},deadlineMs);try{const page=await poll(async()=>{if(childExit){const e=Error(`source exited: ${JSON.stringify(childExit)}`);e.fatal=true;throw e}const pages=await getJson(`http://127.0.0.1:${port}/json/list`);return pages.find(x=>x.type==='page'&&x.webSocketDebuggerUrl)},'source page',Math.min(expires,Date.now()+7000));if(page.url!=='sgccz://game/electron/index.html')throw Error(`unexpected source page ${page.url}`);client=await connect(page.webSocketDebuggerUrl);const evaluate=async expression=>{const r=await client.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};await poll(()=>evaluate(ready),'HallUnit class',Math.min(expires,Date.now()+7000));const result=await evaluate(probe);const hallUnit=path.join(sourceRoot,'recovered-js/modules/game-data/HallUnit.js'),engine=path.join(sourceRoot,'web/cocos2d-js.js');if(result.cases.length!==22||result.cases.some(x=>x.steps.length!==x.deltas.length))throw Error('incomplete controlled fixture');const report={contract:'controlled-source-hall-move-steps-v1',evidenceKind:'actual-source-engine-production-method-controlled-delta',controlledEvidence:true,naturalRun:false,sourceRoot,startedAt:startedAt.toISOString(),completedAt:new Date().toISOString(),source:{hallUnit:{path:hallUnit,sha256:shaFile(hallUnit)},engine:{path:engine,sha256:shaFile(engine)},pathOracle:{path:pathOracleTool,sha256:shaFile(pathOracleTool),evidenceKind:pathOracle.evidenceKind}},...result};fs.writeFileSync(path.join(outputRoot,'source-hall-move-steps.json'),JSON.stringify(report,null,2)+'\n');console.log(`SOURCE_HALL_MOVE_STEPS_OK cases=${result.cases.length}`)}finally{clearTimeout(timer);if(client)client.close();try{process.kill(-child.pid,'SIGTERM')}catch{}await delay(300);try{process.kill(-child.pid,'SIGKILL')}catch{}fs.closeSync(log)}})().catch(e=>{console.error(e.stack||e);process.exitCode=1});
