#!/usr/bin/env node
/* Executes recovered Item, ItemStore and HallCfg factories with a deliberately
 * small data-model surface.  Fixtures drive real constructors/methods. */
import {createRequire} from 'module';import fs from 'fs';import path from 'path';import {fileURLToPath} from 'url';
const require=createRequire(import.meta.url),here=path.dirname(fileURLToPath(import.meta.url)),f=JSON.parse(fs.readFileSync(process.argv[2]));
global.cc={_RF:{push(){},pop(){}}};
const C={ITEM_STORE_COUNT:4,ITEM_PROP_COUNT:4,ITEM_PROP_OFFSET:1000,ITEM_PROP_N:1004,EX_ITEM_OFFSET:2000,ITEM_TYPE:{WEAPONS:0,ARMOR:1,AUXILIARY:2,PROPERTY:3},ITEM_EQUIP_TYPE:{UNKNOW:255,JIANGJIAN_T:9,PAO_T:19,SHAN:2,BAOJIAN:4,JIANGJIAN:6,KAIJIA:10,YIFU:12,PAO:14},ITEM_ATTR_NAME:{NAME:0,INTRO:1,TREASURE:2},ITEM_ATTR_NAME2:{ITEM_TYPE:0,TREASURE:1,VALUE:2,EFFVALUE:3,UPGRADE_ARM:4,PRICE:5,ICON:6,MAX:7},WEAPON_ATTR_INDEX:{ID:0,LV:1,EXP:2,MAX:3},UNIT_ATTR_NAME2:{WQ:100,HJ:110,FZ:120,LV:1},EQUIP_ADD_UNIT_ATTR_FLAG:{ATT:1,SPR:2,DEF:4},MODEL_PROPERTY_INDEX:{COMEQUIP_EXPLIMIT:1,COMEQUIP_UPGRADE:2,SPEEQUIP_EXPLIMIT:3,SPEEQUIP_UPGRADE:4,COMEQUIP_LVLIMIT:5,SPEEQUIP_LVLIMIT:6},GLOBAL_VAR:{XZDJ:1,ITEM_OFFSET:2}};
let table=new Map(),store,unitAttrs=new Map();const model={rFlagAll:()=>true,cheating:()=>{},itemAttr2:(id,k,d=0)=>table.get(id)?.a[k]??d,itemAttr:(id,k,d='')=>k===0?(table.get(id)?.name??d):k===2?(table.get(id)?.treasure??d):d,itemIter:cb=>{for(const id of table.keys())if(cb(0,id))break},property:(k,d=0)=>({1:200,2:6,3:200,4:6,5:9,6:9}[k]??d),getGVars:()=>0,itemAttrFace2:()=>0,unitAttr2:(id,k,d=0)=>unitAttrs.get(`${id}:${k}`)??d,setUnitAttr2:(id,k,v)=>unitAttrs.set(`${id}:${k}`,v),levelFiled:()=>10,unitsIter:()=>{},hasItem:()=>false,refTreasure:()=>{},averageLv:()=>1,cfgItemTypeName:x=>`type${x}`};
let Item,ItemStore,HallCfg;function load(file,deps){let e={};require(path.resolve(here,'../../jojo_mobile/sgccz-desktop/recovered-js/modules/game-data/'+file))((n)=>deps[n]??{}, {},e);return e}
Item=load('Item.js',{Config:C,Instance:{default:{range:(x,a,b)=>Math.max(a,Math.min(b,x))}},ItemStore:{default:{instance:()=>store}},Model:{default:{instance:()=>model}},Unit:{default:{countEquipLevel:()=>1}}}).default;
ItemStore=load('ItemStore.js',{Manager:{getManager:()=>({dispatchEvent:()=>{}})},Config:C,Instance:{default:{range:(x,a,b)=>Math.max(a,Math.min(b,x))}},Item:{default:Item},Model:{default:{instance:()=>model}},Unit:{default:{countEquipLevel:()=>1}}}).default;
HallCfg=load('HallCfg.js',{});
function run(c){table=new Map(c.items.map(x=>[x.id,x]));ItemStore.destoryInstance();store=ItemStore.instance();let out=[];const snap=(s)=>out.push({s,props:c.propertyIds.map(id=>[id,store.propertyCount(id)]),weapons:store.allWeapons(7).map(x=>[x.id(),x.lv(),x.exp()]),hall:{AUTO_CLOSE:HallCfg.SAY_FLAG.AUTO_CLOSE,QI_PAO:HallCfg.SAY_FLAG.QI_PAO,MOVE:HallCfg.RMAPOBJ_ACTION.MOVE}});snap('clear');for(const e of c.events){let p=e.split(':');if(p[0]==='prop')store.pushProperty(+p[1],+p[2]);else if(p[0]==='weapon')store.pushWeapon(+p[1],+p[2],+p[3]);else if(p[0]==='delete')store.delWeaponByPos(+p[1]);else if(p[0]==='item'){let x=new Item(+p[1],+p[2]);out.push({s:e,item:{id:x.id(),type:x.type(),itemType:x.itemType(),phase:x.phase(),flag:x.addAttrFlag(),name:x.name(),price:x.price(),sell:x.sellPrice(),value:x.value(),icon:x.icon(),canDrop:x.canDrop(),lv:x.lv(),exp:x.exp(),nameProperty:x.name_property()}})}snap(e)}return out}
fs.mkdirSync(path.dirname(process.argv[3]),{recursive:true});fs.writeFileSync(process.argv[3],JSON.stringify(Object.fromEntries(f.cases.map(c=>[c.name,run(c)]))));
