#!/usr/bin/env node
/* Factory execution harness: HallLayer event entry plus BattleInit/Sort/Start roster methods. */
const fs=require('fs'),path=require('path'),fixture=JSON.parse(fs.readFileSync(process.argv[2]));
function Node(){this.active=true;this.tag2=0;this.listeners={};this.color=null;this.parent={removeAllChildren(){},addChild(){}};this.width=100} Node.prototype.getContentSize=function(){return{width:100,height:40}};Node.prototype.getComponent=function(){return null};Node.prototype.setPosition=function(p){this.pos=p};
function Button(){this.node=new Node;this.interactable=true}function Label(){this.node=new Node;this.string=''}function Sprite(){this.node=new Node;this.spriteFrame=null}
function U(){this.node=new Node;this.n={};this.c={};this.layers=[];this.ev={};this.dispatch=[];this.sound=[];this.removed=false}U.prototype.onCreate=function(){};U.prototype.onDestroy=function(){};U.prototype.seekNodeByName=function(n){return this.n[n]||(this.n[n]=new Node)};U.prototype.seekCompByName=function(K,n){if(this.c[n])return this.c[n];let v=new K;if(this.n[n])v.node=this.n[n];else this.n[n]=v.node;return this.c[n]=v};U.prototype.addTouchEventListener=function(x,f,p){let n=x.node||x;n.fn=f;n.target=x;n.priority=p};U.prototype.addEventListener=function(n,f){this.ev[n]=f};U.prototype.dispatchEvent=function(n,v){this.dispatch.push([n,v])};U.prototype.dispatchEventOnce=function(n){this.dispatch.push([n])};U.prototype.addLayer=function(n){this.layers.push(n)};U.prototype.removeLayer=function(){};U.prototype.removeFromParent=function(){this.removed=true};U.prototype.playSoundEffect=function(x){this.sound.push(x)};U.prototype._setBg=function(){};U.prototype.eFlag=function(){return 0};U.prototype.rFlag=function(){return 0};U.prototype.getLayer=function(){return{battlePos:()=>null}};U.prototype.convertToWorldSpaceAR=function(){return{x:10,y:40}};
global.cc={_RF:{push(){},pop(){}},_decorator:{ccclass:x=>x,property:()=>()=>{}},Component:U,Node,NodePool:function(){this.put=function(){};this.clear=function(){}},Button,Label,Sprite,color:(r,g,b)=>`${r},${g},${b}`,instantiate:()=>new Node};
function load(folder,file,res){let e={};require(path.resolve(__dirname,'../../jojo_mobile/sgccz-desktop/recovered-js/modules',folder,file))(res,{},e);return e.default}
const cfg={HALL_FLAG:{MENU:1,COMMAND:2,BATTLE:4,ZB:8,MR:16},ENABLED_FEATURE:{TGJQ:1,ZZSJCS:2},SOUND_INDEX:{INIT_BATTLE:7},BATTLE_MINE_N:3,UNIT_ATTR_NAME2:{ATT:1,SPR:2,DEF:3}};
U.LAYER={SkipLayer:'SkipLayer',HallMenuLayer:'HallMenuLayer'};
function hallRes(n){ if(n==='UILayer')return {default:U};if(n==='Config')return cfg;if(n==='Hall')return {default:U};if(n==='Model')return {default:{instance:()=>({eventName:()=> 'E',stageName:()=> 'S'})}};return {default:U}; }
function battleRes(n){
  if(n==='UILayer')return {default:U}; if(n==='Sound')return {default:{getInstance:()=>({stopAllEffects(){global.stopped=true}})}};
  if(n==='Config')return cfg; if(n==='UserDefault')return {default:{getInstance:()=>({setIntegerForKey(){},getIntegerForKey:(_k,d)=>2})}};
  if(n==='Hall')return {default:{LAYER:{HallLayer:'HallLayer',BattleViewLayer:'BattleViewLayer'}}};
  if(n==='Instance')return {default:{LAYER:{BattleSortLayer:'BattleSortLayer',UnitInfoLayer:'UnitInfoLayer'},format:(s,a,b)=>s.replace('%d',a).replace('%d',b),range:(v,_a,max)=>Math.min(v,max)}};
  if(n==='Model')return {default:{instance:()=>({unit:id=>unit(id),battleName:x=>x,unitsIter:fn=>[unit(0),unit(1),unit(2),unit(3)].forEach(fn)})}}; if(n==='BattleUnit')return {default:{}}; return {};
}
const Hall=load('ui','HallLayer.js',hallRes),Init=load('battle','BattleInitLayer.js',battleRes),Sort=load('battle','BattleSortLayer.js',battleRes),Start=load('battle','StartBattleLayer.js',battleRes);
function unit(id){return{id:()=>id,name:()=>`U${id}`,postsName:()=>'',lv:()=>1,exp:()=>0,hp:()=>1,mp:()=>1,wuwei:()=>0,ability:()=>0,mov:()=>0,equip:()=>null}}
function snapStart(x,s){return{step:s,slots:x._selunits.map(a=>a[1]),fights:[...x._fights],label:x._label.string,ok:x._okbtn.interactable,events:x.dispatch.map(a=>a[1])}}
function runStartInit(){
 let x=new Start;x.item1=new Node;x.item1.parent={removeAllChildren(){},addChild(){}};x.item2=new Node;x.content=new Node;x.nodes=[{}, {}, {}];
 x.rFlag=()=>0;x._setBg=()=>{};x.getLayer=()=>({battlePos:()=>null});x._refInfo=()=>{};x._refBtn=()=>{};x._initFightUnit=function(){let t=2;this._sort(t);this._sel(t)};
 x.onCreate({flag:0,enterLimit:[0,3,[2,0],[2]],func(){}});
 return [{step:'create',max:x._max,min:x._min,must:[...x._mastFights],mustJoin:[...x._mastJoin],units:x._units2.map(u=>u.id()),order:x._sort(x._selidx).map(u=>u.id()),button2:x.seekNodeByName('bg/button2').active,sort:x._selidx,descending:x._dsc}]
}
function run(c){if(c.kind==='hall'){let x=new Hall;x._run_Helper=()=>{};x._startBattle=()=>x.layers.push('startBattle');x._openStore=()=>x.layers.push('openStore');x._buyIn=()=>x.layers.push('buyIn');x._sellOut=()=>x.layers.push('sellOut');x.onCreate({hall_flag:c.flag});let out=[{step:'create',flag:x._flag,layers:[...x.layers]}];for(let e of c.events){x.ev.HALL_COMMAND(+e.split(':')[1]);out.push({step:e,flag:x._flag,layers:[...x.layers]})}return out}if(c.kind==='init'){let x=new Init;x.onCreate(c.flag);let out=[{step:'create',flag:x._flag,z:x.node.zIndex,sound:[...x.sound],events:x.dispatch,labels:[x.seekCompByName(Label,'bg/label0').string,x.seekCompByName(Label,'bg/label1').string],attached:!x.removed,stopped:false}];for(let e of c.events){let p=e.split(':');if(p[0]==='load')x.ev.BATTLE_LOAD_BGMAP(p[1]);else x.onDestroy();out.push({step:e,flag:x._flag,z:x.node.zIndex,sound:[...x.sound],events:x.dispatch,labels:[x.seekCompByName(Label,'bg/label0').string,x.seekCompByName(Label,'bg/label1').string],attached:!x.removed,stopped:!!global.stopped})}return out}if(c.kind==='sort'){let x=new Sort,call=[];x.onCreate({pos:{x:10,y:20},func:i=>call.push(i)});let out=[];for(let e of ['create',...c.events]){if(e!=='create'){let p=e.split(':');let n=p[0]==='cancel'?x.seekNodeByName('Panel_cancel'):x.seekCompByName(Button,`button1_${p[1]}`).node;n.fn(n.target,+p[p.length-1])}out.push({step:e,pos:x.seekNodeByName('menu').pos||{x:10,y:20},attached:!x.removed,calls:[...call]})}return out}let x=new Start;x._max=3;x._min=2;x._selunits=[[new Node,-1],[new Node,-1],[new Node,-1]];x._fights=new Set;x._mastFights=new Set;x._units={'1':new Node,'2':new Node};x._label=new Label;x._okbtn=new Button;x._init=true;let out=[snapStart(x,'create')];for(let e of c.events){let p=e.split(':');p[0]==='fight'?x._fight(+p[1]):x._cancel(+p[1]);out.push(snapStart(x,e))}return out}
const out=Object.fromEntries(fixture.cases.map(c=>[c.id,c.kind==='startinit'?runStartInit():run(c)]));fs.mkdirSync(path.dirname(process.argv[3]),{recursive:true});fs.writeFileSync(process.argv[3],JSON.stringify(out));
