#!/usr/bin/env node
/* Actual recovered factory runner for the item/equipment layer family. */
const fs=require('fs'),path=require('path'),F=JSON.parse(fs.readFileSync(process.argv[2]));
function N(){this.children=[];this.active=true;this.tag2=0;this._c=new Map()}function L(){this.node=new N;this.string=''}function B(){this.node=new N;this.interactable=true}function P(){this.node=new N;this.progress=0}function S(){this.node=new N}function V(){this.node=new N}V.prototype.scrollToTop=function(){}
function Base(){this.n={};this.layers=[];this.events=[];this.toasts=[];this.dead=false;this._handle=null;this._handle3=null;this.m_manager={itemDir:x=>'i/'+x};this._color1='c1';this._color2='c2';this._color3='c3';this._unit=unit(this)}
Base.prototype._setBg=function(){};Base.prototype.seekNodeByName=function(x,p){let z=p||this;if(!z.n)z.n={};return z.n[x]||(z.n[x]=new N)};Base.prototype.seekCompByName=function(K,x,p){p=p||this.seekNodeByName(x);let k=K.name+x;if(!p._c.has(k)){let q=new K;q.node=p;p._c.set(k,q)}return p._c.get(k)};Base.prototype.addTouchEventListener=function(n,h){n.listener=h};Base.prototype.addLayer=function(l,a){this.layers.push({layer:l,args:a&&typeof a==='object'?{txt:a.txt??null,values:a.values??null}:null});this.answer=typeof a==='function'?a:a&&(a.func||a.fn)};Base.prototype.removeFromParent=function(){this.dead=true};Base.prototype.cmdToast=function(x){this.toasts.push(x)};Base.prototype.dispatchEvent=function(x,v){this.events.push(x+':'+v)};Base.prototype.playSoundEffect=function(x){this.events.push('sound:'+x)};Base.prototype.loadByUrl=function(f){f({ret:'sprite'})};Base.prototype.scheduleOnce=function(f){this._handle3?this._handle3=f:this._handle=f};Base.prototype.unschedule=function(){};Base.prototype._unHandle=function(){this._handle=void 0};Base.prototype.rFlag=()=>0;Base.prototype.addEventListener=function(){};Base.prototype.refUnitInfo=function(){this.events.push('ref')};Base.prototype._ref=function(){this._bags=this.bags?this.bags():[]};Base.prototype._values=()=>Array(8).fill(0);Base.prototype.onCreate=function(){this._ref()};
function unit(l){return{id:()=>7,equipItem:(id,lv,slot)=>l.events.push('equip:'+id+':'+slot),equip:s=>s===0?item(80,false):item(81,false),unload:s=>{l.events.push('unload:'+s);return[81,2,0]},leave:()=>false}}
function item(id,prop){return{id:()=>id,type:()=>prop?3:0,itemType:()=>1,canDrop:()=>true,lv:()=>2,value:()=>3,addAttrFlag:()=>1,name:()=>`I${id}`,name_property:()=>`P${id}`,skillIntro:()=>'',price:()=>5,intro:()=>`intro${id}`,expLimit:()=>10,exp:()=>2,icon:()=>id,postsCanEquip:()=>true,deleteFromStore:()=>{global.layer.events.push('delete:'+id)}}}
global.cc={_RF:{push(){},pop(){}},_decorator:{ccclass:x=>x,property:()=>()=>{}},Component:Base,Label:L,Button:B,ProgressBar:P,Sprite:S,ScrollView:V,SpriteFrame:class{},NodePool:class{clear(){}put(){}get(){return new N}size(){return 0}},instantiate:()=>new N,color:(...x)=>x};
const C={ITEM_TYPE:{PROPERTY:3,ARMOR:2},POSTS_ATTR_NAME:{NAME:0},ITEM_CATEGORY_FLAG:{WEAPONS:1,ARMOR:2,AUXILIARY:4},ENABLED_FEATURE:{ZZSJCS:1},SOUND_INDEX:{PUSH_STORE:1}};const I={default:{LAYER:{MsgBox:'MsgBox',MsgBox2:'MsgBox2',ItemLayer:'ItemLayer',ExclusiveLayer:'ExclusiveLayer'}}};const Store={default:{instance:()=>({allProperty:()=>[item(10,true),item(11,true)],propertyCount:()=>2,allWeapons:()=>[item(55,false)],hasWeaponSpace:()=>true,hasWeapon:()=>null,delWeaponByPos:()=>{}})}};const Model={default:{instance:()=>({cfgItemTypeName:()=> 'type',cfgUnitAttrName:()=> 'attr',postsIter:f=>[0,1].forEach(f),postsAttr:()=> 'post',unitsIter:f=>f(unit(global.layer)),unit:()=>null})}};
function load(name,base=Base){let ex={};require(path.resolve(__dirname,'../../jojo_mobile/sgccz-desktop/recovered-js/modules/ui/'+name+'.js'))(n=>({UILayer:{default:base},InfoBaseLayer:{default:base},UnitInfoBaseLayer:{default:base},Config:C,Instance:I,ItemStore:Store,Model,Hall:{default:{LAYER:{DialogueLayer:'DialogueLayer',EquipConfirmLayer:'EquipConfirmLayer'}}},UserDefault:{default:{getInstance:()=>({getStringForKey:()=>null,setStringForKey:()=>{}})}}}[n]||{}),{},ex);return ex.default}
const Item=load('ItemLayer'),Use=load('UsePropertyLayer'),Confirm=load('EquipConfirmLayer'),Equip=load('EquipLayer');
function snap(l,step){return{step,dead:l.dead,layers:l.layers.map(x=>({layer:x.layer,args:x.args})),events:[...l.events],toasts:[...l.toasts],sel:l._sel??null,bags:(l._bags||[]).map(x=>x.id()),buttons:(l._btns||[]).map(x=>x.interactable)}}
function run(c){let l;if(c.kind==='item'){l=new Item();global.layer=l;l.onCreate({item:item(c.item.id,c.item.property)})}else if(c.kind==='use'){l=new Use();global.layer=l;l.onCreate({func:x=>l.events.push('use:'+(x?x.id():'none'))})}else if(c.kind==='confirm'){l=new Confirm();global.layer=l;l.onCreate({values:c.values,func:()=>l.events.push('confirmed')})}else{l=new Equip();global.layer=l;l.onCreate('all')};let out=[snap(l,'create')];for(let e of c.events){let p=e.split(':');if(p[0]==='click'){let n=p[1]==='0'?l.seekNodeByName('Panel_cancel'):l.seekNodeByName('button'+p[1],l.seekNodeByName('bg1'));n.tag2=+p[1];l._onClick(n,+p[2])}else if(p[0]==='row'){l._onClick({tag2:+p[1]},+p[2])}else if(p[0]==='cancel'){let n=l.seekNodeByName('Panel_cancel');n.listener(n,+p[1])}else if(p[0]==='button'){let n=l.seekCompByName(B,'button'+p[1],l.seekNodeByName('baseInfo'));n.node.tag2=+p[1];n.listener(n,+p[2])}else if(p[0]==='tab')l._select(+p[1]);else if(p[0]==='clickItem')l.clickItem(item(+p[1],false));else if(p[0]==='equip')l.equip(+p[1],+p[2]);else if(p[0]==='answer'){let f=l.answer;l.answer=null;f&&f(+p[1])};out.push(snap(l,e))}return out}
fs.mkdirSync(path.dirname(process.argv[3]),{recursive:true});fs.writeFileSync(process.argv[3],JSON.stringify(Object.fromEntries(F.cases.map(c=>[c.name,run(c)]))));
