#!/usr/bin/env node
/* Minimal Cocos execution of recovered ui/LoadGameLayer.js. */
const fs=require('node:fs'),path=require('node:path');const fixture=JSON.parse(fs.readFileSync(process.argv[2],'utf8')),output=process.argv[3];
class Node{constructor(name=''){this.name=name;this.children=[];this.active=true;this.tag2=0;this.parent=null}set parent(p){this._parent=p;if(p&&!p.children.includes(this))p.children.push(this)}get parent(){return this._parent}getComponent(){return{spriteFrame:null}}}
class Pool{constructor(){this.a=[]}clear(){this.a=[]}put(n){if(n.parent){const i=n.parent.children.indexOf(n);if(i>=0)n.parent.children.splice(i,1)}n._parent=null;this.a.push(n)}get(){return this.a.pop()}size(){return this.a.length}}
let cloneId=0;global.cc={Component:class{},Node,NodePool:Pool,Sprite:class{},Label:class{},Toggle:class{},SpriteFrame:class{},instantiate:n=>new Node(n.name+'-clone'+(++cloneId)),color:n=>n,_RF:{push(){},pop(){}},_decorator:{ccclass:x=>x,property:()=>()=>{}}};let current,activeLayer;
function raw(x){if(!x||x.invalid)return x&&x.invalid==='short'?'x':'broken';return JSON.stringify({time:x.time,name:x.name,model:{version:x.version||0,stage:x.stage},...(x.battle?{battle:x.battle}:{})})}
function Layer(){this.m_manager={loadGame:(i)=>raw(current.slots.find(x=>x.index===i))};this.events=[];this.comps={};this.nodes={};this.toggles={};}
Layer.prototype._setBg=function(){};Layer.prototype.onDestroy=function(){};Layer.prototype.rFlag=function(){return current.feature?1:0};Layer.prototype.addTouchEventListener=function(c,fn){c.listener=fn};Layer.prototype.removeFromParent=function(){this.removed=true};Layer.prototype.cmdToast=function(x){this.events.push('toast:'+x)};Layer.prototype.replaceScene=function(x){this.events.push('scene:'+x)};Layer.prototype.addLayer=function(kind,p){this.confirm={...p,index:+p.txt.match(/No\.(\d+)/)[1]-1};this.events.push('confirm:'+this.confirm.index)};
Layer.prototype.seekNodeByName=function(n){return this.nodes[n]||(this.nodes[n]=new Node(n))};Layer.prototype.seekCompByName=function(_,n,p){const key=(p?p.name+'/':'')+n;if(!this.comps[key]){const node=this.seekNodeByName(key);this.comps[key]={node,string:'',spriteFrame:null,isChecked:false};if(/^toggle\d+$/.test(n))this.toggles[n]=this.comps[key]}return this.comps[key]};
const out={};require(path.resolve(__dirname,'../../jojo_mobile/sgccz-desktop/recovered-js/modules/ui/LoadGameLayer.js'))(n=>{if(n==='UILayer')return{default:Layer};if(n==='Manager')return{getManager:()=>({getUpdateInt:()=>current.versionCode,resetGame:()=>{}}),default:{isWin32:()=>false}};if(n==='UserDefault')return{default:{getInstance:()=>({getIntegerForKey:()=>current.savedPage,setIntegerForKey:(_,v)=>current.savedPage=v})}};if(n==='Config')return{ENABLED_FEATURE:{ZDBHSW:1},MODEL_PROPERTY_INDEX:{STAGE_N:1},STAGE:{HALL_SCENE:'HALL',BATTLE_SCENE:'BATTLE'}};if(n==='Instance')return{default:{LAYER:{MsgBox:'MsgBox'}}};if(n==='Model')return{default:{instance:()=>({loadGame:()=>activeLayer.events.push('loadModel'),incStage:()=>activeLayer.events.push('incStage')})}};return{default:{}}},{},out);
const Source=out.default;function rows(l){return l._content.children.map(n=>{const a=l.seekCompByName(cc.Label,'label0',n),b=l.seekCompByName(cc.Label,'label1',n),c=l.seekCompByName(cc.Label,'label2',n);return{index:n.tag2,number:a.string,stage:b.string,name:c.string}})}
function run(spec){current={...spec,savedPage:spec.savedPage};const l=new Source,lcontent=new Node('content'),item=new Node('item');activeLayer=l;item.parent=lcontent;l.item=item;l.imgs=[{},{}];l.onCreate();const trace=[];function snap(step){const events=l.events.splice(0);trace.push({step,page:l._page,rows:rows(l),toggles:l.seekNodeByName('toggleContainer').active!==false,attached:!l.removed,confirmation:l.confirm?l.confirm.index:null,events})}function fire(e){const[a,b]=e.split(':');if(a.startsWith('row')){const n=l._content.children.find(x=>x.tag2===+a.slice(3));n.listener(n,+b)}else if(a.startsWith('page'))l.toggles['toggle'+(+a.slice(4)+1)].listener({node:l.toggles['toggle'+(+a.slice(4)+1)].node},+b);else if(a==='confirm'){const p=l.confirm;l.confirm=null;p.fn(+b)}else if(a==='cancel')l.nodes['bg1/button0'].listener(l.nodes['bg1/button0'],+b);snap(a+'-'+b)}snap('create');spec.events.forEach(fire);return{case:spec.id,trace}}
const result=fixture.cases.map(run);fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(result));console.log(JSON.stringify(result));
