#!/usr/bin/env node
/* Recovered Magic, MagickListLayer and MagicLayer under a minimal Cocos UI. */
const fs=require('node:fs'),path=require('node:path');const f=JSON.parse(fs.readFileSync(process.argv[2],'utf8')),outFile=process.argv[3];
class Node{constructor(){this.parent=null;this.tag2=null;this.color=null;this.active=true;this._button={interactable:true};}getComponent(){return this._button}}
function Base(){this.nodes={};this.comps={};this.events=[];this.rows=[]}Base.prototype._setBg=function(x){this.bg=x};Base.prototype.seekNodeByName=function(n,p){const k=(p?"p/":"")+n;return this.nodes[k]||(this.nodes[k]=new Node)};Base.prototype.seekCompByName=function(_,n,p){const k=(p?"p/":"")+n;return this.comps[k]||(this.comps[k]={node:new Node,progress:0,string:'',setMaterial(){}})};Base.prototype.addTouchEventListener=function(){};Base.prototype.loadByUrl=function(cb,url){this.events.push('asset:'+url);cb({ret:{}})};Base.prototype.scheduleOnce=function(fn){this._scheduled=fn};Base.prototype.unschedule=function(){this._scheduled=null};Base.prototype.removeFromParent=function(){this.removed=true;this.events.push('remove')};Base.prototype.addLayer=function(k,v){this.events.push('layer:'+k+':'+v.id());this.layer=v};
global.cc={_RF:{push(){},pop(){}},_decorator:{ccclass:x=>x,property:()=>()=>{}},Label:class{},Sprite:class{},ProgressBar:class{},Button:class{},SpriteFrame:class{},Material:class{},color:(...x)=>x,instantiate:n=>new Node};
const base=path.resolve(__dirname,'../../jojo_mobile/sgccz-desktop/recovered-js/modules/battle');function load(n,deps){const o={};require(path.join(base,n+'.js'))(x=>deps[x]||{}, {},o);return o.default}
function run(c){const table={};c.magics.forEach(m=>table[m.id]=m);const config={MAGIC_ATTR_NAME:{NAME:0,INTRO:1},MAGIC_ATTR_NAME2:{TYPE:2,TARGET:3,CATEGORY:4,HITAREA:5,EFFAREA:6,EXPENDMP:7,ICON:8,MEFF:9,POWER:10,HARM:11,CONDITION:12,AI_USE:13,HITRATELIMIT:14}};const model={default:{instance:()=>({magicAttr:(id,k,d)=>k===0?table[id].name:k===1?table[id].intro:d,magicAttr2:(id,k)=>({5:table[id].hit,6:table[id].eff,7:table[id].cost,8:table[id].icon,10:table[id].power})[k]})}};
 const Magic=load('Magic',{Config:config,Model:model});const MagicLayer=load('MagicLayer',{UILayer:{default:Base}});let stored=JSON.stringify(c.uses);const user={default:{getInstance:()=>({getStringForKey:()=>stored,setStringForKey:(_,v)=>stored=v})}};const List=load('MagickListLayer',{UILayer:{default:Base},UserDefault:user,Instance:{default:{LAYER:{MagicLayer:'MagicLayer'}}}});
 const magics=c.magics.map(x=>new Magic(x.id));const char={mp_cur:()=>c.mp,mp:()=>c.maxMp,unit:()=>({name:()=>"caster"}),magics:()=>magics};const list=new List;list.grays=[{},{}];list.onCreate({c:char,fn:m=>list.events.push(m?'selected:'+m.id():'cancelled')});const sorted=magics.filter(m=>m.expendMp()!=255).sort((a,b)=>(c.uses[b.id()]||0)-(c.uses[a.id()]||0)||a.id()-b.id());let layer=null;const trace=[];function snap(step){trace.push({step,rows:sorted.map(m=>({id:m.id(),enabled:c.mp>=m.expendMp()})),preview:list._bars[1].progress,removed:!!list.removed,uses:JSON.parse(stored),layer:layer?{name:layer.seekCompByName(cc.Label,'label',layer.seekNodeByName('bg1')).string,assets:layer.events.filter(x=>x.startsWith('asset:')),removed:!!layer.removed}:null,events:list.events.splice(0)})}
 for(const raw of c.events){const [a,b]=raw.split(':');if(a==='START'||a==='END'){list._onClick(sorted[+b].tag2?sorted[+b]:Object.assign(new Node,{tag2:sorted[+b]}),a==='START'?0:2)}else if(a==='tick'){list._scheduled?.();if(list.layer){layer=new MagicLayer;layer.onCreate(list.layer)}}else if(a==='cancel')list._onCloseClick(null,b==='END'?2:1);else if(a==='magic')layer?._onCloseClick(null,b==='END'?2:1);snap(raw)}return{case:c.id,trace}}
const o=f.cases.map(run);fs.mkdirSync(path.dirname(outFile),{recursive:true});fs.writeFileSync(outFile,JSON.stringify(o));console.log(JSON.stringify(o));
