#!/usr/bin/env node
// Actual recovered factory runner: only Cocos surfaces invoked by MiniMapLayer are mocked.
// Button listener is kept both on the component and its node by this factory-local prototype hook.
const fs=require('fs'),path=require('path'),f=JSON.parse(fs.readFileSync(process.argv[2]));let R;
function N(n=''){this.name=n;this.children=[];this.position={x:0,y:0};this.size={width:80,height:80};this.cs=[]}N.prototype.getContentSize=function(){return this.size};N.prototype.setContentSize=function(a,b){this.size=typeof a==='object'?a:{width:a,height:b}};N.prototype.setPosition=function(x,y){this.position=typeof x==='object'?{x:x.x,y:x.y}:{x,y}};N.prototype.setAnchorPoint=N.prototype.stopAllActions=function(){};N.prototype.runAction=function(a){this.action=a};N.prototype.addComponent=function(K){let x=new K;x.node=this;this.cs.push(x);return x};N.prototype.getComponent=function(K){return this.cs.find(x=>x instanceof K)||this.addComponent(K)};Object.defineProperty(N.prototype,'parent',{set(p){if(p&&!p.children.includes(this))p.children.push(this)}});
function S(){}S.Type={SLICED:1};S.SizeMode={CUSTOM:1};function B(){this.node=new N('btn');let a=new N(),b=new N();a.parent=this.node;b.parent=a}function P(){this.a=[]}P.prototype.put=function(x){this.a.push(x)};P.prototype.get=function(){return this.a.pop()||new N()};P.prototype.size=function(){return this.a.length};P.prototype.clear=function(){this.a=[]};
function U(){this.node=new N();this.node.setContentSize(800,600);this.n={};this.c={};this.e={};this.m_ud={getIntegerForKey:()=>R.setting}}U.prototype.onDestroy=function(){this.dead=true};U.prototype.seekNodeByName=function(n,p){if(n==='bg/map'){let b=this.seekNodeByName('bg');return this.n.map||(this.n.map=new N('map'),this.n.map.parent=b)}if(n==='bg/weather')return this.n.weather||(this.n.weather=new N('weather'));return this.n[n]||(this.n[n]=new N(n))};U.prototype.seekCompByName=function(K,n,p){if(this.c[n])return this.c[n];let x=new K;if(K!==B)x.node=this.seekNodeByName(n,p);this.c[n]=x;return x};U.prototype.addTouchEventListener=function(n,h){n.listener=h};U.prototype.addEventListener=function(n,h){this.e[n]=h};U.prototype.loadByUrl=function(h){R.load=h};
U.prototype.addTouchEventListener=function(n,h){n.listener=h;if(n.node)n.node.listener=h};
global.cc={_RF:{push(){},pop(){}},_decorator:{ccclass:x=>x,property:()=>()=>{}},Component:U,Node:N,NodePool:P,Sprite:S,Button:B,SpriteFrame:function(){},instantiate:()=>new N(),v2:(x,y)=>({x,y}),v3:(x,y)=>({x,y}),size:(width,height)=>({width,height}),delayTime:()=>0,hide:()=>0,show:()=>0,callFunc:()=>0,sequence:a=>({a}),moveTo:()=>({easing(){return this}}),easeQuarticActionOut:()=>0};let E={};require(path.resolve(__dirname,'../../jojo_mobile/sgccz-desktop/recovered-js/modules/ui/MiniMapLayer.js'))(n=>n==='UILayer'?{default:U}:n==='Config'?{GAME_SETTING:'x',SETTING_FLAG:{MINI_MAP:16},BATTLE_CAMP:{MINE:1,FRIEND:2},BATTLE_UNIT_STATUS2:{MS:0}}:n==='BattleConfg'?{NOTIFY_CHANGE_FLAG:{VISIBLE:1,POS:2,MOVE:4,ACTION:8,CTRL:16,CAMP:32},UNIT_STATUS_LIFT:{NORMAL:0}}:{default:{}},{},E);
cc.v3=(x,y)=>typeof x==='object'?{x:x.x,y:x.y}:{x,y};
function c(id,c,a,s,f,x,y){return{visible:()=>true,index:()=>id,pos:()=>({x,y}),type:()=>c==='mine'?1:c==='friend'?2:3,unit:()=>({isFamous:()=>f}),isAction:()=>a==='action',status:()=>s==='ms'?1:0,isControl:()=>s==='control'}}
function state(l,k,n){let map={};for(let[id,x]of Object.entries(l._map))map[id]={x:x.position.x,y:x.position.y,frame:x.getComponent(S).spriteFrame};let hs=l._mapNode.children.filter(x=>x.action).map(x=>({x:x.position.x,y:x.position.y,w:x.size.width,h:x.size.height,actions:x.action?.a?.length||0}));return{step:k,show:l._show,loaded:!!l._size,size:l._size||null,bg:l._size?l._bg.position:null,box:l._size?l._box.position:null,weather:l.seekCompByName(S,'bg/weather').spriteFrame??null,pool:l._nodePool.size(),map,highlights:hs,baseDestroyed:!!l.dead,callbackCount:n}}
function run(q){R={setting:q.setting};let n=0,l=new E.default();l.sfs=Array.from({length:16},(_,i)=>'sf'+i);l.weather=Array.from({length:8},(_,i)=>'weather'+i);let mn=l.seekNodeByName('bg/map');for(let i=0;i<q.initialPoolNodes;i++)new N('i'+i).parent=mn;l.onCreate({mapIndex:0,weather:q.weather,callback:()=>n++});let o=[state(l,'create',n)];for(let z of q.events){let p=z.split(':');if(p[0]==='load')R.load({ret:{_originalSize:{width:+p[1],height:+p[2]}}});else if(p[0]==='scroll')l.e.MAP_SCROLLING({x:+p[1],y:+p[2]});else if(p[0]==='weather')l.e.WEATHER_CHANGE(+p[1]);else if(p[0]==='highlight')l.e.BATTLE_HIGHT_LIGHT({x:+p[1],y:+p[2],w:+p[3],h:+p[4]});else if(p[0]==='touch')l.c.btn.node.listener(null,+p[1]);else if(p[0]==='visible'){let x=c(+p[1],p[2],p[3],p[4],p[5]==='true',+p[6],+p[7]);l.e.CHARACTER_CHANGE({c:x,flag:1})}else if(p[0]==='hide')l.e.CHARACTER_CHANGE({c:{visible:()=>false,index:()=>+p[1]},flag:1});else if(p[0]==='move')l.e.CHARACTER_CHANGE({c:{visible:()=>true,index:()=>+p[1]},flag:4,pos:{x:+p[2],y:+p[3]}});else if(p[0]==='ref'){let x=c(+p[1],p[2],p[3],p[4],p[5]==='true',0,0);l.e.CHARACTER_CHANGE({c:x,flag:8})}else if(p[0]==='pos'){let x=c(+p[1],'mine','normal','normal',false,+p[2],+p[3]);l.e.CHARACTER_CHANGE({c:x,flag:2,old_pos:{x:0,y:0}})}else if(p[0]==='destroy')l.onDestroy();o.push(state(l,z,n))}return o}fs.writeFileSync(process.argv[3],JSON.stringify(Object.fromEntries(f.cases.map(q=>[q.name,run(q)]))));
