#!/usr/bin/env node
/* Actual recovered platform factories with a deliberately small Cocos/native boundary mock.
 * Native operations are recorded as boundary calls, never emulated as device APIs. */
const fs=require('fs'),path=require('path'),crypto=require('crypto'),fixture=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
class Node{constructor(n=''){this.name=n;this.active=true;this.tag2=0;this.listener=null;this.children=[];this.parent=null;this.components={};}getComponent(K){return this.components[K.name]||(this.components[K.name]=new K(this))}}
class Label{constructor(n){this.node=n;this.string=''} } class RichText extends Label{} class Button{constructor(n){this.node=n;this.interactable=false}} class Sprite{constructor(n){this.node=n}} class NodePool{clear(){}} class VideoPlayer{constructor(){this.clip=null;this.plays=0}play(){this.plays++}}
function Layer(){this.nodes={};this.comps={};this.layers=[];this.cmds=[];this.events=[];this.dead=false;this.listeners={};this.m_manager=manager;this.node={getComponent:()=>this.video||(this.video=new VideoPlayer())}}
Layer.prototype.seekNodeByName=function(n){return this.nodes[n]||(this.nodes[n]=new Node(n))};Layer.prototype.seekCompByName=function(K,n){return this.comps[K.name+n]||(this.comps[K.name+n]=new K(this.seekNodeByName(n)))};Layer.prototype.addTouchEventListener=function(n,f){(n.node||n).listener=f};Layer.prototype.addLayer=function(n,p){this.layers.push([Array.isArray(n)?n[1]:n,p&&p.txt]);};Layer.prototype.addCmd=function(x){this.cmds.push(x)};Layer.prototype.dispatchEvent=function(x){this.events.push(x);(this.listeners[x]||[]).forEach(f=>f())};Layer.prototype.addEventListener=function(x,f){(this.listeners[x]||(this.listeners[x]=[])).push(f)};Layer.prototype.removeEventListener=function(x){delete this.listeners[x]};Layer.prototype.removeFromParent=function(){this.dead=true};Layer.prototype._setBg=function(){};Layer.prototype.onDestroy=function(){};Layer.prototype.schedule=function(_,interval,repeat,delay){(this.schedules||(this.schedules=[])).push(["schedule",interval,repeat,delay])};Layer.prototype.scheduleOnce=function(_,delay){(this.schedules||(this.schedules=[])).push(["scheduleOnce",delay])};Layer.prototype.unschedule=function(){};Layer.prototype.playBackgroundSound=function(){};Layer.prototype.hasLayer=()=>false;Layer.prototype.getLayer=()=>null;Layer.prototype.replaceScene=function(x){this.scene=x};Layer.prototype.getMeta=function(k,d){return meta[k]??d};Layer.prototype.rFlag=()=>0;Layer.prototype.cmdToast=function(x){this.toast=x};Layer.prototype.fastInitList=function(xs,_,f){this.fastItems=[...xs];xs.forEach(f)};Layer.prototype.loadByUrl=function(cb){cb(videoError?{err:1}:{ret:'logo-clip'})};
const store={},native=[];let meta={},manager={launch:'',m_deviceId:'',launchGame(){return this.launch},setGameSpeed(){native.push('setGameSpeed')},currentSdk(){return {haveLogin(){return false},login(){},devicesId(){return Promise.resolve('desktop')}}},resetGame(){},setLaunchGame(x){native.push('setLaunch:'+x)},restart(){native.push('restart')},getWritablePath(){return '/w'},resetLaunchGame(){native.push('resetLaunch')}};
global.cc={_RF:{push(){},pop(){}},_decorator:{ccclass:x=>x,property:()=>()=>{}},Label,RichText,Button,Sprite,NodePool,Node,VideoPlayer,Asset:class{},Prefab:class{},instantiate:x=>x,director:{getScheduler:()=>({setTimeScale:x=>native.push('time:'+x)})},sys:{os:'DESKTOP',OS_ANDROID:'ANDROID'}};
global.jsb={fileUtils:{getWritablePath:()=>'/w/',writeStringToFile:(x,p)=>native.push('write:'+p+':'+x)}};
function loadModule(name){const e={};require(path.resolve(__dirname,'../../jojo_mobile/sgccz-desktop/recovered-js/modules/platform/'+name+'.js'))(n=>{if(n==='UILayer'||n==='UIScene')return {default:Layer};if(n==='UserDefault')return {default:{getInstance:()=>({getIntegerForKey:(k,d)=>store[k]??d,setIntegerForKey:(k,v)=>store[k]=v,getStringForKey:(k,d)=>store[k]??d,setStringForKey:(k,v)=>store[k]=v,deleteValueForKey:k=>delete store[k]})}};if(n==='Manager')return {default:{isAndroid:()=>false,isIos:()=>false,isWin32:()=>true,helper:x=>x.cmd==='getMac1'?{code:macError,data:macs}:{code:0,data:[]},getManager:()=>manager,getInstance:()=>manager}};if(n==='MD5')return {default:class{hex_md5(x){return crypto.createHash('md5').update(x).digest('hex')}}};if(n==='SdkBase')return {SdkBase};if(n==='CmdLayer')return {default:{getConfig:()=>new Map([[0,{gold:currentMoney}]])}};if(n==='EngineCfg')return {CMDS:{END_GAME:'END_GAME'},BG_SOUND_IDX:{START:0}};if(n==='Instance')return {default:{LAYER:{MsgBox:'MsgBox',LoadGameLayer:'LoadGame',SettingLayer:'Setting',StartItemLayer:'StartItem',LoadingLayer:'Loading'},instance:()=>({endingFlag:()=>0,getMineFloor:()=>mineFloor}),destoryInstance(){}}};if(n==='Config')return {STAGE:{HALL_SCENE:'HALL'},BG_SOUND_IDX:{START:0}};if(n==='Model')return {default:{instance:()=>({endingFlag:()=>0,getMineFloor:()=>mineFloor}),destoryInstance(){}}};return {}},{},e);return e}
function load(name){return loadModule(name).default};let mineFloor=0,currentMoney=0,macs=[],macError=0,videoError=false;const Privacy=load('PrivacyLayer'),Statement=load('StatementLayer'),Version=load('VersionInfoLayer'),Install=load('InstallLayer'),Hot=load('HotUpdateLayer'),Login=load('Login'),SdkBase=loadModule('SdkBase').SdkBase,Taptap=loadModule('Taptap').Taptap,Video=load('VideoLayer');const hit=(x,e)=>x.listener&&x.listener(x,e);const snap=(x,kind,more={})=>({kind,attached:!x.dead,layers:x.layers,cmds:x.cmds,events:x.events,native:[...native],...more});
async function run(c){Object.keys(store).forEach(k=>delete store[k]);native.length=0;manager.launch=c.launch||'';mineFloor=c.mineFloor||0;currentMoney=c.money||0;macs=c.macs||[];macError=c.macError||0;videoError=!!c.loadError;meta={app_id:c.appId};if(c.kind==='privacy'){let called=0,x=new Privacy();x.onCreate(()=>called++);hit(x.seekNodeByName('Logo_12-1/button'+c.event[0]),+c.event[2]);return [snap(x,c.kind,{called,privacy:store.Privacy||null})]};if(c.kind==='statement'){store.PLAYER_TIMER=c.playerTimer;x=new Statement();x.onCreate();hit(x.seekNodeByName('Logo_12-1/button'+c.event[0]),+c.event[2]);return [snap(x,c.kind,{time:x._time,statement:store.STATEMENT||0,scheduleSpecs:x.schedules||[]})]};if(c.kind==='version'){if(c.version)store.VERSION_INFO=c.version;x=new Version();x.onCreate();hit(x.seekNodeByName('Logo_12-1/button0'),+c.event[2]);return [snap(x,c.kind,{lines:x.fastItems.length,first:x.fastItems[0]})]};if(c.kind==='install'){x=new Install();x.onCreate();hit(x.seekNodeByName('Logo_12-1/button'+c.event[0]),+c.event[2]);return [snap(x,c.kind,{buttons:[0,1,2,3,4].map(i=>x.seekNodeByName('Logo_12-1/button'+i).active)})]};if(c.kind==='hot'){x=new Hot();x._btns=[new Node(),new Node(),new Node(),new Node()];if(c.event==='over'){x._over();return [snap(x,c.kind,{})]}x._setBtnFalg(5,true);let z={ini:x.parseIni(c.ini),diff:x.isDiffGreaterThanOneDay(c.left,c.right),buttons:x._btns.map(q=>q.active)};return [snap(x,c.kind,z)]};if(c.kind==='login'){x=new Login();x._flag=0;x.m_manager=manager;let f=x._getFloor();let check=x._checkFloor();return [snap(x,c.kind,{floor:f,check,toast:x.toast||null})]};if(c.kind==='sdk'){if(c.saved)store.DEVICE_ID=c.saved;let x=new SdkBase(),id=await x.devicesId();return [snap(new Layer(),c.kind,{device:id,saved:store.DEVICE_ID||null})]};if(c.kind==='taptap'){let x=new Taptap();return [snap(new Layer(),c.kind,{haveLogin:x.haveLogin()})]};if(c.kind==='video'){let called=0,x=new Video();x.onCreate({index:7,func:()=>called++});x.onEvent(null,c.event);return [snap(x,c.kind,{called,clip:x.video.clip,plays:x.video.plays,toast:x.toast||null})]};return []}
(async()=>{const out={};for(const c of fixture.cases)out[c.id]=await run(c);fs.mkdirSync(path.dirname(process.argv[3]),{recursive:true});fs.writeFileSync(process.argv[3],JSON.stringify(out));})();
