#!/usr/bin/env python3
"""Post-process injected placeholder KDoc comments in Kotlin files.

This script rewrites only comments that were generated by the bulk annotator
("구체적인 보강이 필요" placeholder + generic parameter 템플릿) to richer,
Korean descriptions based on the adjacent declaration signature.
"""

import re
from pathlib import Path
from typing import List, Optional, Tuple


CLASS_KW_RE = re.compile(
    r"(?P<mods>(?:(?:public|private|protected|internal|open|abstract|sealed|data)\s+)*)"
    r"(?P<kind>class|interface|object|enum\\s+class|data\\s+class|sealed\\s+class|annotation\\s+class)"
    r"\\s+(?P<name>`?[^\s(:]+`?)",
)
FUN_RE = re.compile(
    r"(?P<mods>(?:public|private|protected|internal|override|open|inline|suspend|operator|tailrec|crossinline|noinline|infix|expect|actual|lateinit|private\s+set|\s)*)"  # noqa: E501
    r"\\bfun\\s+(?P<name>`?[^\s(<]+`?)\\s*(?P<type_params><[^>]*>)?\\s*\\((?P<params>.*?)\\)\\s*(?::\\s*(?P<ret>[^=\{]+))?",
    re.DOTALL,
)


NON_PUBLIC_MODS = {"private", "protected", "internal"}


def has_placeholder(block: str) -> bool:
    return (
        "클래스/타입의 책임, 입력 파라미터, 상태 영향도를 기준으로 세부 보강이 필요합니다." in block
        or "동작 결과의 도메인 값입니다." in block
    )


def split_params(raw: str) -> List[str]:
    if not raw.strip():
        return []

    parts = []
    cur = []
    depth_angle = depth_paren = depth_brace = 0

    for ch in raw:
        if ch == "<":
            depth_angle += 1
        elif ch == ">":
            depth_angle = max(0, depth_angle - 1)
        elif ch == "(":
            depth_paren += 1
        elif ch == ")":
            depth_paren = max(0, depth_paren - 1)
        elif ch == "{":
            depth_brace += 1
        elif ch == "}":
            depth_brace = max(0, depth_brace - 1)

        if ch == "," and depth_angle == depth_paren == depth_brace == 0:
            token = "".join(cur).strip()
            if token:
                parts.append(token)
            cur = []
        else:
            cur.append(ch)

    token = "".join(cur).strip()
    if token:
        parts.append(token)
    return parts


def guess_param_desc(name: str, ptype: str) -> str:
    n = name.lower()
    t = ptype.replace("`", "").strip().lower()

    if n in {"id", "idx", "index"}:
        return "대상 식별자를 지정합니다."
    if n.endswith("id"):
        return "대상 또는 리소스 식별자를 지정합니다."
    if n in {"name", "title", "text", "label", "message"}:
        return "표시/문구에 사용되는 문자열 값을 전달합니다."
    if "boolean" in t or "bool" in n or n.startswith("is") or n.startswith("has"):
        return "조건 분기/동작 제어 플래그를 전달합니다."
    if n in {"x", "y", "dx", "dy"}:
        return "좌표/오프셋 계산에 사용되는 수치 값을 전달합니다."
    if n in {"fn", "callback", "listener"}:
        return "콜백 함수를 주입해 결과 또는 터치 이벤트 처리를 위임합니다."
    if n in {"unit", "units"}:
        return "전투 유닛 데이터와 상태를 전달하거나 조회의 기준이 됩니다."
    if "list" in n or "items" in n:
        return "여러 항목을 일괄 처리하기 위한 컬렉션 값입니다."
    if "map" in n:
        return "키-값 매핑으로 조회/적용 규칙을 전달합니다."
    if "list" in n or "array" in n:
        return "요청/렌더링 대상을 열거하는 목록입니다."
    if "skill" in n:
        return "기술/효과 계산에 사용되는 값 맵 또는 속성 정보를 전달합니다."
    if "event" in n:
        return "이벤트 타입 또는 이벤트 처리 코드를 전달합니다."

    return "구현 규격에 따라 동작 파라미터로 사용됩니다."


def build_param_docs(raw: str) -> List[str]:
    params = split_params(raw)
    if not params:
        return [" * - 입력 파라미터: 없음"]

    out = [" * ### 파라미터"]
    for part in params:
        token = part.strip()
        if not token:
            continue
        if ":" in token:
            name = token.split(":", 1)[0].strip().split()[-1].strip("`")
            ptype = token.split(":", 1)[1].strip()
            if "=" in ptype:
                ptype = ptype.split("=", 1)[0].strip()
            out.append(f" * - `{name}` (`{ptype}`): {guess_param_desc(name, ptype)}")
        else:
            name = token.strip("`")
            out.append(f" * - `{name}`: 구현 규격의 파라미터입니다.")
    return out


def build_class_comment(kind: str, name: str) -> List[str]:
    short_name = name.strip("`")
    return [
        "/**",
        f" * 공개 {kind} `{short_name}`",
        " *",
        f" * 이 타입은 애플리케이션 공개 API의 공개 타입입니다. `{short_name}`의 역할은 컨텍스트에 따라 상태 보존, 생성/조회/흐름 제어를 담당합니다.",
        " *",
        " * ### 사용 목적",
        " * - 외부 모듈에서 생성/호출될 수 있으며, 도메인 동작(상태 변경, 조회, 렌더/로직 분기)에 사용됩니다.",
        " *",
        " */",
        "",
    ]


def build_fun_comment(name: str, params: str, ret: Optional[str]) -> List[str]:
    fun_name = name.strip("`")
    ret_type = (ret or "Unit").strip()
    if not ret_type:
        ret_type = "Unit"

    lines = [
        "/**",
        f" * 공개 함수 `{fun_name}`",
        " *",
        " * ### 동작 요약",
        f" * `{fun_name}` 함수는 현재 타입의 공개 동작 계약에 따라 호출이 수행되며, 전달된 파라미터로 계산/조회/이벤트 전달을 처리합니다.",
        " *",
    ]
    lines.extend(build_param_docs(params))
    lines.extend(
        [
            " *",
            " * ### 응답 스펙",
            f" * - 반환 타입: `{ret_type}`",
            " * - 반환값: 호출 결과의 계약 값입니다. `Unit`인 경우에는 상태 변경 또는 외부 연동이 발생해도 값 자체는 반환하지 않습니다.",
            " */",
            "",
        ]
    )
    return lines


def is_public(mods: str) -> bool:
    tokens = set(mods.split())
    return not (NON_PUBLIC_MODS & tokens)


def collect_decl(lines: List[str], start_idx: int) -> Tuple[int, str, str]:
    # start_idx는 @Annotation 이후 첫 선언 라인을 가리킵니다.
    header_parts: List[str] = []
    i = start_idx
    while i < len(lines):
        header_parts.append(lines[i].strip())
        flat = " ".join(header_parts)
        if "{" in lines[i] or "=" in lines[i] or lines[i].strip().endswith(","):
            # likely complete for most Kotlin declaration headers
            return i, flat, lines[i]
        if ")" in lines[i] and ("=" in lines[i] or "{" in lines[i]):
            return i, flat, lines[i]
        # safety: include at most 6 lines
        if len(header_parts) >= 6:
            return i, flat, lines[i]
        i += 1
    return i - 1, " ".join(header_parts), lines[start_idx] if start_idx < len(lines) else ""


def process_file(path: Path) -> bool:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()

    out: List[str] = []
    i = 0
    changed = False

    while i < len(lines):
        line = lines[i]
        if line.lstrip().startswith("/**"):
            j = i
            block = []
            while j < len(lines):
                block.append(lines[j])
                if lines[j].strip().endswith("*/"):
                    break
                j += 1

            block_text = "\n".join(block)
            next_idx = j + 1

            if has_placeholder(block_text):
                k = next_idx
                while k < len(lines) and lines[k].strip() == "":
                    k += 1
                # skip annotations
                while k < len(lines) and lines[k].lstrip().startswith("@"):
                    k += 1

                decl_end, flat_decl, _ = collect_decl(lines, k)
                # class-like declaration
                cls_m = CLASS_KW_RE.search(flat_decl)
                if cls_m and is_public(cls_m.group("mods") or ""):
                    kind = cls_m.group("kind")
                    name = cls_m.group("name")
                    out.extend(build_class_comment(kind, name))
                    out.extend(lines[k:decl_end + 1])
                    changed = True
                    i = decl_end + 1
                    continue

                fun_m = FUN_RE.search(flat_decl)
                if fun_m and is_public(fun_m.group("mods") or ""):
                    params = fun_m.group("params") or ""
                    ret = fun_m.group("ret") or "Unit"
                    out.extend(build_fun_comment(fun_m.group("name"), params, ret))
                    out.extend(lines[k:decl_end + 1])
                    changed = True
                    i = decl_end + 1
                    continue

                # not matched, keep original block
                out.extend(lines[i:j + 1])
                i = j + 1
                continue

            out.extend(lines[i:j + 1])
            i = j + 1
            continue

        out.append(line)
        i += 1

    if changed:
        path.write_text("\n".join(out) + "\n", encoding="utf-8")
    return changed


def main(path_file: str) -> int:
    paths = [line.strip() for line in Path(path_file).read_text(encoding="utf-8").splitlines() if line.strip()]
    count = 0
    for p in paths:
        path = Path(p)
        if not path.exists() or path.suffix.lower() != ".kt":
            continue
        if process_file(path):
            count += 1
    return count


if __name__ == "__main__":
    import sys

    if len(sys.argv) != 2:
        raise SystemExit("usage: refine_kdoc_comments.py <file-list>")
    print(main(sys.argv[1]))
