#!/usr/bin/env node
const fs=require('fs'),path=require('path');const f=JSON.parse(fs.readFileSync(process.argv[2],'utf8')),dst=process.argv[3];
function N(){this.children=[];this.active=true;this.tag2=0;this._parent=null;this.sprite={spriteFrame:null}}Object.defineProperty(N.prototype,'parent',{get(){return this._parent},set(p){if(this._parent){let i=this._parent.children.indexOf(this);if(i>=0)this._parent.children.splice(i,1)}this._parent=p;if(p&&!p.children.includes(this))p.children.push(this)}});N.prototype.getComponent=function(){return this.sprite};function Pool(){this.x=[]}Pool.prototype.put=function(x){x.parent=null;this.x.push(x)};Pool.prototype.get=function(){return this.x.pop()};Pool.prototype.size=function(){return this.x.length};Pool.prototype.clear=function(){this.x=[]};function Label(){this.string='';this.node=new N()}function Button(){this.node=new N()}function Toggle(){this.node=new N();this.isChecked=false}function Sprite(){}
const raw=new Map(f.saves.map(s=>[s.index,JSON.stringify({time:s.time,name:s.name,model:s.game?{game:{stage:s.stage}}:{property2:[0,s.stage]}})]));
function L(){this.nodes={};this.comps=[];this.events=[];this.dialog=null;this.m_manager={loadGame:i=>raw.get(i)}}L.prototype.onDestroy=function(){};L.prototype._setBg=function(){};L.prototype.rFlag=function(){return this.flag};L.prototype.addTouchEventListener=function(x,fn){x.listener=fn};L.prototype.removeFromParent=function(){this.removed=true;this.events.push('removeFromParent')};L.prototype.removeLayer=function(x){this.removed=true;this.events.push('removeLayer:'+x)};L.prototype.dispatchEvent=function(e,a){this.events.push('dispatch:'+e+':'+a.idx);a.func()};L.prototype.addLayer=function(x,a){this.dialog=a;this.events.push('msgbox:'+(a.flag?'complete':'confirm')+(a.txt.match(/No\.(\d+)/)?.[1]?':'+a.txt.match(/No\.(\d+)/)[1]:''))};L.prototype.seekNodeByName=function(n){if(n==='bg1/box2/scrollview/view/content/item'){let x=this.nodes.item||(this.nodes.item=new N());if(!x.parent)x.parent=this.nodes.content||(this.nodes.content=new N());return x}return this.nodes[n]||(this.nodes[n]=new N())};L.prototype.seekCompByName=function(K,n,p){let c=new K();c._name=n;c._parent=p;this.comps.push(c);return c};
global.cc={Component:L,NodePool:Pool,Label,Button,Toggle,Sprite,SpriteFrame:class{},instantiate:()=>new N(),_RF:{push(){},pop(){}},_decorator:{ccclass:x=>x,property:()=>()=>{}}};
// Cocos components belong to their node, not to its mutable `tag2`.  The
// SaveLayer pool retags nodes between pages, so keying this mock by tag2
// incorrectly reuses a previous slot's label and falsifies the source trace.
L.prototype.seekCompByName=function(K,n,p){
  if(!p){this.cache||(this.cache=new Map());const k=n+K.name;if(!this.cache.has(k)){const c=new K();c._name=n;c._parent=p;this.cache.set(k,c);this.comps.push(c)}return this.cache.get(k)}
  p._componentCache||(p._componentCache=new Map());const k=n+K.name;
  if(!p._componentCache.has(k)){const c=new K();c._name=n;c._parent=p;p._componentCache.set(k,c);this.comps.push(c)}
  return p._componentCache.get(k)
};
const flush=async()=>{await Promise.resolve();await Promise.resolve();await Promise.resolve()};
async function run(c){const ex={};let layer;require(path.resolve(__dirname,'../../jojo_mobile/sgccz-desktop/recovered-js/modules/ui/SaveLayer.js'))(n=>{if(n==='UILayer')return{default:L};if(n==='UserDefault')return{default:{getInstance:()=>({getIntegerForKey:()=>c.savedPage,setIntegerForKey:(_,v)=>layer.stored=v})}};if(n==='Config')return{MODEL_PROPERTY_INDEX:{STAGE_N:1},ENABLED_FEATURE:{ZDBHSW:1}};if(n==='Instance')return{default:{LAYER:{MsgBox:'MsgBox',SaveLayer:'SaveLayer'}}};return{default:{}}},{},ex);let cb=0;layer=new ex.default();layer.flag=c.pagesEnabled?1:0;layer.onCreate({tip:c.tip,func:()=>{cb++;layer.events.push('callback')}});const trace=[];function snap(step){const rows=layer._content.children.map(n=>{const z=layer.comps.filter(c=>c._parent===n&&c instanceof Label);return{index:n.tag2,number:z.find(x=>x._name==='label0').string,stage:z.find(x=>x._name==='label1').string,name:z.find(x=>x._name==='label2').string}});trace.push({step,page:layer._page,storedPage:layer.stored??c.savedPage,toggles:layer.nodes.toggleContainer.active,attached:!layer.removed,pending:layer.dialog?layer.dialog.txt:null,rows,events:layer.events.splice(0),callbacks:cb})}snap('create');for(const e of c.events){let p=e.split(':');if(p[0]==='row'){layer._content.children.find(n=>n.tag2===+p[1]).listener(layer._content.children.find(n=>n.tag2===+p[1]),+p[2])}else if(p[0]==='page'){let t=layer.comps.find(x=>x instanceof Toggle&&x.node.tag2===+p[1]);t?.listener?.(t,+p[2])}else if(p[0]==='cancel'){layer.comps.find(x=>x instanceof Button)?.listener(null,+p[1])}else {let d=layer.dialog;layer.dialog=null;d?.fn(+p[1])}await flush();snap(e)}return{id:c.id,trace}}
(async()=>{let out=[];for(const c of f.cases)out.push(await run(c));fs.mkdirSync(path.dirname(dst),{recursive:true});fs.writeFileSync(dst,JSON.stringify(out));console.log(JSON.stringify(out))})().catch(e=>{console.error(e);process.exit(1)});
