#!/usr/bin/env node
/* Recovered PyManager/RControlScript factories, with binary/file/delegate
 * boundaries made explicit as deterministic mocks. */
const fs=require('fs'),path=require('path'),F=JSON.parse(fs.readFileSync(process.argv[2]));global.cc={_RF:{push(){},pop(){}},_decorator:{ccclass(){},property(){}}};
function load(file,deps){const e={};require(path.resolve(__dirname,'../../jojo_mobile/sgccz-desktop/recovered-js/modules/scenario-runtime/'+file+'.js'))(n=>deps[n]||{}, {}, e);return e}
const Py=load('PyManager',{Tool:{default:{random:(a,b)=>a}}}).default;global.window={SGCCZPythonSource:{create:()=>({loadSource(){},reset(){},setArgv(){},call(){},running:()=>false,ret:()=>42})}};const R=load('RControlScript',{PyManager:{default:Py}}).RControlScript;
function str(s){return [...Buffer.from(s),0]}function integer(n){return[n]}function bin(valid=true){if(!valid)return{_buffer:Uint8Array.from([...str('bad')])};const b=[...str('python'),...integer(1),...str('main'),...integer(4),...str('2'),...str('3'),...str('True'),...str('<other>'),...integer(0),...integer(0),...integer(0),...integer(1),...integer(7),...integer(0),...integer(8),0,0,0,1,17,0,10,0];return{_buffer:Uint8Array.from(b)}}
function drain(p){while(p.running())p.run()}
function run(c){if(c.kind==='lifecycle'){let next=0;const p=new Py({next:()=>next++});p.pause();p._setIsPause();p.resume();p.resume();p.destory();p.reset();return{builtins:['print','label','goto','range','len','call','hasFunc','int','str','random','max','min','list'].map(k=>Object.hasOwn(p._module,k)),pauseAfterResume:p.pauseState(),next,afterDestroy:p.running(),afterReset:p.running(),saveLoad:[typeof p.save,typeof p.load]}}
if(c.kind==='invalid'){const p=new Py({next(){}});return{code:p.loadBin(bin(false),'bad.py'),name:p.name(),functions:Object.keys(p._funcs)}}
if(c.kind==='bytecode'){const p=new Py({next(){}});const code=p.loadBin(bin(true),'sum.py');const f=p._funcs.main;p.call('main');drain(p);return{code,name:p.name(),consts:f.consts.map(x=>x&&x.__pyType?{type:x.__pyType,value:x.address??x.tuple}:x),labels:f.labels,bytes:f.bytes,stack:[...p._stack],line:p.line(),hasMain:p.haveFunction('main')}}
if(c.kind==='method_error'){const p=new Py({next(){}});let error='';try{p.loadMethod({},'missing')}catch(e){error=String(e)}return{error,saveLoad:[typeof p.save,typeof p.load]}}
if(c.kind.startsWith('rcontrol')){let calls=[],cb=[];const py={reset:()=>calls.push('reset'),setArgv:x=>calls.push('argv:'+JSON.stringify(x??null)),call:(n,a)=>calls.push('call:'+n+':'+JSON.stringify(a)),running:()=>{const v=py._runs++<1;return v},_runs:0,run:()=>calls.push('run'),pauseState:()=>py._runs===1,_setIsPause:()=>calls.push('setPause'),ret:()=>42,setHelper:h=>calls.push('helper'),loadSource:(s,n)=>calls.push('loadSource:'+n+':'+s)};let info=c.kind==='rcontrol_existing'?py:null;const delegate={scriptInfo:()=>info,loadPythonSource:(n,h)=>{calls.push('file:'+n);return'PY'},setPyManager:p=>{calls.push('setPy');info=p},setScriptInfo:p=>calls.push('setInfo')};const g=R();let q=g.next();q=g.next({delegate,helper:{next:()=>calls.push('helper.next')},filename:'scene.py',params:[1,2],argv:{x:1},func_name:'main',func:v=>cb.push(v)});while(!q.done)q=g.next();return{calls,callback:cb,done:q.done}}
}
fs.mkdirSync(path.dirname(process.argv[3]),{recursive:true});fs.writeFileSync(process.argv[3],JSON.stringify(Object.fromEntries(F.cases.map(c=>[c.name,run(c)]))));
