#!/usr/bin/env node
/* Actual recovered-factory trace: UnitInfoBase-derived Buy, Sell and Reward.
 * Minimal Cocos nodes only provide APIs reached by source; state is never
 * reimplemented here. */
import {createRequire} from 'module'; import fs from 'fs'; import path from 'path'; import {fileURLToPath} from 'url';
const require=createRequire(import.meta.url),here=path.dirname(fileURLToPath(import.meta.url)),fixture=JSON.parse(fs.readFileSync(process.argv[2]));
let log=[],queue=[],overlays=[],state,traceRewardVisual=false;
function Node(name=''){this.name=name;this.node=this;this.children=[];this._active=true;this.tag2=0;this.interactable=true;this.color={};this.spriteFrame=null;this.string=''}
Object.defineProperty(Node.prototype,'active',{get(){return this._active},set(v){this._active=v;if(traceRewardVisual)log.push(['active',this.name,!!v])}});
Node.prototype.getComponent=function(){return this};Node.prototype.getContentSize=()=>({height:20});Node.prototype.setContentSize=()=>{};
function Pool(){this.a=[]}Pool.prototype.get=function(){return this.a.pop()||new Node('pooled')};Pool.prototype.put=function(n){this.a.push(n)};Pool.prototype.size=function(){return this.a.length};Pool.prototype.clear=function(){this.a=[]};
function Base(){this._listeners=[];this._events={};this.content=new Node('content');this.m_scene={addLayer:(kind,arg)=>{overlays.push({kind,arg});log.push(['addLayer',kind,normal(arg)]);return {setTxt:x=>log.push(['setTxt',x]),removeFromParent:()=>log.push(['dialogRemove'])}},removeLayer:x=>log.push(['removeLayer',normal(x)]),hasLayer:()=>false,getLayer:()=>null};this.m_manager={itemDir:x=>x,removeCmdByTarget:()=>{},m_imgs:[]};this.m_ud={getIntegerForKey:()=>0};this.m_id=9;this.isValid=true}
Base.prototype.seekNodeByName=function(n){return new Node(n)};Base.prototype.seekCompByName=function(_c,n){return new Node(n)};Base.prototype.addTouchEventListener=function(node,fn,priority){node.__touch=fn;this._listeners.push({node,fn,priority})};Base.prototype.addEventListener=function(n,fn){this._events[n]=fn};Base.prototype.dispatchEvent=function(n,p){log.push(['event',n,normal(p)])};Base.prototype.scheduleOnce=function(fn,sec){queue.push(fn);log.push(['schedule',sec])};Base.prototype.unschedule=function(fn){queue=queue.filter(x=>x!==fn)};Base.prototype.addLayer=function(k,a){return this.m_scene.addLayer(k,a)};Base.prototype.getLayer=function(k){return this.m_scene.getLayer(k)};Base.prototype.hasLayer=function(k){return this.m_scene.hasLayer(k)};Base.prototype.removeLayer=function(k){return this.m_scene.removeLayer(k)};Base.prototype.removeFromParent=function(){log.push(['removed'])};Base.prototype._setBg=function(x){log.push(['bg',x])};Base.prototype.playSoundEffect=function(x){log.push(['sound',x])};Base.prototype.playBackgroundSound=function(x){log.push(['bgSound',x])};Base.prototype.cmdToast=function(x){log.push(['toast',x])};Base.prototype.headDir=x=>x;Base.prototype.loadByUrl=function(cb,url){if(traceRewardVisual)log.push(['assetComplete',url]);cb({err:false,ret:{getOriginalSize:()=>({width:10,height:10})}})};Base.prototype.fastInitList=function(xs,_n,fn){xs.forEach(fn)};Base.prototype.convertToWorldSpaceAR=()=>({y:100});Base.prototype.onCreate=function(){};Base.prototype.onDestroy=function(){};
global.cc={_RF:{push(){},pop(){}},_decorator:{ccclass:x=>x,property:()=>()=>{}},Component:Base,Node,NodePool:Pool,Label:Node,Sprite:Node,SpriteFrame:Node,Button:Node,ProgressBar:Node,color:(...x)=>x,instantiate:()=>new Node('clone')};
const TYPE={AUXILIARY:1,PROPERTY:2},config={ITEM_TYPE:TYPE,UNIT_ATTR_NAME2:{ATT:0,SPR:1,DEF:2,CRI:3,MOR:4},SOUND_INDEX:{ADD_MONEY:'ADD_MONEY',PUSH_STORE:'PUSH_STORE'},BG_SOUND_IDX:{REWARD:'REWARD'}};
class Item{constructor(id){this.d=state.by.get(+id)}id(){return this.d.id}name(){return this.d.name}type(){return this.d.type==='property'?2:this.d.type==='auxiliary'?1:3}price(){return this.d.price}sellPrice(){return this.d.sell}lv(){return this.d.lv??1}exp(){return this.d.exp??0}expLimit(){return this.d.limit??10}icon(){return this.d.id}name_property(){return ''}deleteFromStore(){state.weaponDeleted.push(this.d.id);log.push(['weaponDelete',this.d.id])}}
function unit(){return {name:()=>"조조",postsName:()=>"군주",id:()=>state.unitId,lv:()=>1,exp:()=>0,expLimit:()=>1,hp:()=>1,mp:()=>1,ability:()=>1,mov:()=>1,equip:()=>null,canEquip:()=>0,equipItem:(id,lv,type,flag,exp)=>{log.push(['equipItem',id,lv,type,flag,exp??null]);return [0,0,0]}}}
const modules={};function load(name,file,deps){let ex={};require(path.resolve(here,'../../jojo_mobile/sgccz-desktop/recovered-js/modules/ui/'+file))((n)=>deps[n]??{default:Base},{},ex);modules[name]=ex.default}
load('UnitInfoBase','UnitInfoBaseLayer.js',{UILayer:{default:Base},Config:config,Instance:{default:{LAYER:{ItemLayer:'ItemLayer'}}},Model:{default:{instance:()=>({unitsIter:cb=>cb(unit()),unitAttrFace2:()=>0})}},Hall:{default:{LAYER:{UnitListLayer:'UnitListLayer',EquipConfirmLayer:'EquipConfirmLayer'}}}});
const common={
 Config:config, Item:{default:Item},
 ItemStore:{default:{instance:()=>({
   propertyCount:id=>state.props.get(id)||0,
   pushProperty:(id,n)=>{state.props.set(id,(state.props.get(id)||0)+n);log.push(['property',id,n])},
   allWeapons:()=>state.items.filter(x=>x.type!=='property').map(x=>new Item(x.id)),
   allProperty:()=>state.items.filter(x=>x.type==='property'&&(state.props.get(x.id)||0)>0).map(x=>new Item(x.id))
 })}},
 Model:{default:{instance:()=>({
   money:()=>state.money, addMoney:n=>{state.money+=n;log.push(['money',n,state.money])},
   itemTotal:x=>({tn:state.props.get(x.id?.()??x)||0,cn:state.props.get(x.id?.()??x)||0}),
   unitsIter:cb=>cb(unit()), unitAttrFace2:()=>0
 })}},
 Instance:{default:{LAYER:{ItemLayer:'ItemLayer',MsgBox2:'MsgBox2',MsgBox3:'MsgBox3'},range:(n,a,b)=>Math.max(a,Math.min(b,n))}},
 Hall:{default:{LAYER:{DialogueLayer:'DialogueLayer'}}}
};
load('Buy','BuyLayer.js',{...common,UnitInfoBaseLayer:{default:modules.UnitInfoBase}});load('Sell','SellLayer.js',common);load('Reward','RewardLayer.js',{Manager:{default:{helper:x=>log.push(['helper',x.cmd])}},UILayer:{default:Base},Config:config,Item:{default:Item}});
function normal(x){if(typeof x==='function')return '[callback]';if(!x||typeof x!=='object')return x;if(x instanceof Item)return x.id();if(Array.isArray(x))return x.map(normal);return Object.fromEntries(Object.entries(x).filter(([k])=>!['node','children','__touch'].includes(k)).map(([k,v])=>[k,normal(v)]))}function flush(){while(queue.length)queue.shift()()}
function start(c){log=[];queue=[];overlays=[];state={money:c.money,unitId:c.unitId,items:c.items,by:new Map(c.items.map(x=>[x.id,x])),props:new Map(c.items.filter(x=>x.type==='property').map(x=>[x.id,c.owned])),weaponDeleted:[]}}
function snap(step,x={}){return {step,money:state.money,properties:Object.fromEntries([...state.props]),weaponDeleted:state.weaponDeleted,actions:log.slice(),overlays:overlays.map(x=>({kind:x.kind,arg:normal(x.arg)})),...x}}
function run(c){start(c);let out=[],buy=new modules.Buy();buy.content=new Node('content');buy.content2=new Node('content2');buy.onCreate({unit_id:c.unitId,item_ids:c.items.map(x=>x.id)});out.push(snap('buy:create',{factory:'BuyLayer',baseLifecycle:!!buy._units,buyRows:(buy._bags2||[]).map(x=>x.id())}));let sell=new modules.Sell();sell.onCreate(c.unitId);out.push(snap('sell:create',{factory:'SellLayer',sellTab:sell._sel}));let reward=new modules.Reward();traceRewardVisual=c.events.includes('reward:cards');reward.onCreate({...c.reward,func:()=>log.push(['rewardCallback'])});traceRewardVisual=false;out.push(snap('reward:create',{factory:'RewardLayer',helper:!!reward._helper}));for(const event of c.events){const p=event.split(':');if(event==='reward:advance'||event==='reward:cards'){traceRewardVisual=event==='reward:cards';if(event==='reward:cards'&&!reward._helper)flush();let z=reward._listeners.find(x=>x.node.name==='Panel_cancel');z.fn(z.node,2);flush();traceRewardVisual=false}else if(p[0]==='buy'&&p[1]==='equip'){buy.clickItem(new Item(+p[2]))}else if(p[0]==='buy'&&p[1]==='equipMsgBox2'){overlays.filter(x=>x.kind==='MsgBox2').at(-1)?.arg(+p[2])}else if(p[0]==='buy'&&(p[1]==='press'||p[1]==='hold')){if(!buy._bags2){buy.sel(1);buy._bags2=c.items.filter(x=>x.type==='property'&&x.price!==255).sort((a,b)=>a.id-b.id).map(x=>new Item(x.id));buy._items2=buy._bags2.map((_,i)=>Object.assign(new Node('buy-row'),{tag2:i}))}let ix=buy._bags2.findIndex(x=>x.id()===+p[2]),n=buy._items2[ix];buy.onClick2(n,0);out.push(snap(event+':begin',{delayed:true}));if(p[1]==='hold')flush();else buy.onClick2(n,2)}else if(p[0]==='buy'&&p[1]==='msgbox3'){overlays.filter(x=>x.kind==='MsgBox3').at(-1)?.arg.func(+p[2])}else if(p[0]==='buy'&&p[1]==='msgbox2'){overlays.filter(x=>x.kind==='MsgBox2').at(-1)?.arg(+p[2])}else if(p[0]==='sell'&&p[1]==='tab'){sell.sel(+p[2])}else if(p[0]==='sell'&&(p[1]==='press'||p[1]==='hold')){let bags=sell._sel===0?sell._bags1:sell._bags2,items=sell._sel===0?sell._items1:sell._items2,ix=bags.findIndex(x=>x.id()===+p[2]),n=items[ix]||new Node('sell-row');n.tag2=ix;sell.onClick(n,0);out.push(snap(event+':begin',{delayed:true}));if(p[1]==='hold')flush();else sell.onClick(n,2)}else if(p[0]==='sell'&&p[1]==='msgbox3'){overlays.filter(x=>x.kind==='MsgBox3').at(-1)?.arg.func(+p[2])}else if(p[0]==='sell'&&p[1]==='msgbox2'){overlays.filter(x=>x.kind==='MsgBox2').at(-1)?.arg(+p[2])}else if(event==='sell:cancel')sell._cancelClick(null,2);out.push(snap(event,{rewardHelper:!!reward._helper,buyRows:(buy._bags2||[]).map(x=>x.id()),sellRows:(sell._sel===0?(sell._bags1||[]):(sell._bags2||[])).map(x=>x.id())}))}return out}
fs.mkdirSync(path.dirname(process.argv[3]),{recursive:true});fs.writeFileSync(process.argv[3],JSON.stringify(Object.fromEntries(fixture.cases.map(c=>[c.name,run(c)]))));
