#!/usr/bin/env node
/* Executes recovered ui/TreasureLayer.js with only its invoked Cocos surface. */
import { createRequire } from 'module';
import { fileURLToPath } from 'url';
const require=createRequire(import.meta.url);
const fs=require('fs'),path=require('path'),__dirname=path.dirname(fileURLToPath(import.meta.url)),fixture=JSON.parse(fs.readFileSync(process.argv[2]));let data;
let nodeId=0;function Node(name=''){this.name=name;this.uid=++nodeId;this.children=[];this.tag2=0;this._c={}}Object.defineProperty(Node.prototype,'parent',{set(p){this._parent=p;if(p&&!p.children.includes(this))p.children.push(this)}});
function Label(){this.string=''} function Sprite(){this.spriteFrame=null} function Pool(){this.a=[]}Pool.prototype.get=function(){return this.a.pop()||new Node('row')};Pool.prototype.put=function(x){this.a.push(x)};Pool.prototype.clear=function(){this.a=[]};Pool.prototype.size=function(){return this.a.length};
function U(){this.m_manager={itemDir:x=>'item/'+x};this.isValid=true;this.layers=[];this.nodes={};this.comps={}}U.prototype.onDestroy=function(){this.destroyed=true};U.prototype._setBg=function(){};U.prototype.seekNodeByName=function(name,parent){let key=(parent?parent.uid+'/':'')+name;return this.nodes[key]||(this.nodes[key]=new Node(name))};U.prototype.seekCompByName=function(K,name,parent){let node=parent||this.seekNodeByName(name);let key=node.uid+'|'+name+'|'+K.name;return this.comps[key]||(this.comps[key]=new K())};U.prototype.addTouchEventListener=function(node,fn){node.listener=fn};U.prototype.fastInitList=function(ids,n,fn){ids.forEach(fn)};U.prototype.loadByUrl=function(fn){fn({ret:'frame'})};U.prototype.addLayer=function(layer,arg){this.layers.push({layer,item:arg.item.x?arg.item.x.id:arg.item.id})};U.prototype.removeFromParent=function(){this.removed=true};
global.cc={_RF:{push(){},pop(){}},_decorator:{ccclass:x=>x,property:()=>()=>{}},Component:U,NodePool:Pool,Label,Sprite,SpriteFrame:function(){},instantiate:()=>new Node('clone')};let exports={};
function run(c){data=c;require(path.resolve(__dirname,'../../jojo_mobile/sgccz-desktop/recovered-js/modules/ui/TreasureLayer.js'))(n=>{
 if(n==='UILayer')return{default:U};if(n==='UserDefault')return{default:{getInstance:()=>({getStringForKey:()=>JSON.stringify(c.discovered)})}};
 if(n==='Config')return{ITEM_ATTR_NAME:{TREASURE:'treasure'},ITEM_TYPE:{PROPERTY:1}};
 if(n==='Item')return{default:class {constructor(id){this.x=c.treasures.find(x=>x.id===id)}name(){return this.x.name}type(){return this.x.property?1:2}itemType(){return this.x.id}skillIntro(){return this.x.description}icon(){return this.x.icon}}};
 if(n==='Model')return{default:{instance:()=>({itemIter:fn=>c.treasures.forEach(x=>fn({treasure:true},x.id)),cfgItemTypeName:id=>c.treasures.find(x=>x.id===id).description})}};
 if(n==='Instance')return{default:{LAYER:{ItemLayer:'ItemLayer'}}};return{}},{},exports);let l=new exports.default();l.onCreate();function st(step){let content=l.seekNodeByName('bg1/scrollview/view/content');let rows=content.children.map(n=>{let a=l.seekCompByName(Label,'label0',n).string||null,b=l.seekCompByName(Label,'label1',n).string||null;return a&&a.match(/No\.(\d+)/)?{id:n.tag2,found:true,number:+a.match(/No\.(\d+)/)[1],label0:a,label1:b}:null}).filter(Boolean);for(let x of c.treasures.filter(x=>!rows.some(r=>r.id===x.id)))rows.push({id:x.id,found:false,number:null,label0:null,label1:null});return{step,title:l.seekCompByName(Label,'bg1/label').string,rows,removed:!!l.removed,route:l.layers.length?l.layers.at(-1).item:null}}let trace=[st('create')];for(let e of c.events){if(e==='cancel')l.seekNodeByName('Panel_cancel').listener(null,2);else if(e==='button7')l.seekNodeByName('bg1/button7').listener(null,2);else if(e.startsWith('tap:')){let n=l.seekNodeByName('bg1/scrollview/view/content').children.find(n=>n.tag2===+e.slice(4));if(n&&n.listener)n.listener(n,2)}trace.push(st(e))}return trace}fs.writeFileSync(process.argv[3],JSON.stringify(Object.fromEntries(fixture.cases.map(c=>[c.name,run(c)]))));
