#!/usr/bin/env node
/* Executes recovered UnitInfoLayer listeners with the JSON shared by Kotlin. */
const path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');
const fixture=JSON.parse(fs.readFileSync(process.argv[2],'utf8')),output=process.argv[3]; let featureEnabled=false;
class Node { constructor(name=''){this.name=name;this.active=true;this.children=[];this.tag2=0;this.interactable=true;this.parent=null} set parent(p){this._parent=p;if(p&&!p.children.includes(this))p.children.push(this)}get parent(){return this._parent}removeAllChildren(){this.children.splice(0)}setContentSize(){}}
class Pool {constructor(){this.items=[]}clear(){this.items=[]}put(n){if(n.parent){const i=n.parent.children.indexOf(n);if(i>=0)n.parent.children.splice(i,1)}n._parent=null;this.items.push(n)}size(){return this.items.length}get(){return this.items.pop()}}
global.cc={Component:class{},Node,NodePool:Pool,instantiate:()=>new Node('magicClone'),_RF:{push(){},pop(){}},Color:{BLACK:{},BLUE:{},RED:{}},color(){return{}},Button:class{},Label:class{},Sprite:class{},ProgressBar:class{},SpriteFrame:class{},_decorator:{ccclass:x=>x,property:()=>()=>{}}};
function Layer(){this.m_ud={value:0,getIntegerForKey:()=>this.m_ud.value,setIntegerForKey:(_,v)=>this.m_ud.value=v};this._nodePool=new Pool;this.buttonComps={};this.equipComps={};}
Layer.prototype.onDestroy=function(){};Layer.prototype._setBg=function(){};Layer.prototype.eFlag=function(){return this.editEnabled?1:0};Layer.prototype.removeFromParent=function(){this.removed=true};
Layer.prototype.addLayer=function(kind,payload){let route,value='',unit=-1,index=-1;if(kind==='Feats'){route='FEATS';unit=payload.id();index=8}else if(kind==='JiQi'){route='JIQI';unit=payload.unit().id();index=9}else if(kind==='Edit'){route='EDIT';const b=payload.battleUnit;unit=(b?b.unit():payload.unit).id();index=10;value=b?'battleUnit':'unit'}else if(kind==='Item'){route='ITEM';value=payload.item.name();index=this._lastEquipmentSlot;unit=this._unit.id()}else if(kind==='Magic'){route='MAGIC';value=payload.name();index=this._lastMagicRow;unit=this._unit.id()}this.routes=(this.routes||[]).concat([{route,index,value,unit}])};
Layer.prototype.addTouchEventListener=function(c,fn){c.listener=fn};Layer.prototype.loadByUrl=function(cb){cb({err:true})};Layer.prototype.headDir=function(){return''};
Layer.prototype.seekNodeByName=function(n,parent){if(n==='bg1/panel4/scrollview/view/content'){if(!this.magicContent){this.magicContent=new Node(n);new Node('magicTemplate').parent=this.magicContent}return this.magicContent}const key=(parent?parent.name+'/':'')+n;const x=this.nodes||(this.nodes={});return x[key]||(x[key]=new Node(key))};
Layer.prototype.seekCompByName=function(_,n,p){const key=(p?p.name+'/':'')+n,x=this.comps||(this.comps={});if(!x[key]){const node=this.seekNodeByName(n,p);x[key]={node,string:'',progress:0,spriteFrame:null};const button=n.match(/(?:^|\/)button\d+$/);if(n==='Panel_cancel'||button)this.buttonComps[button?button[0].split('/').pop():n]=x[key];if(/^node\d+\/bg\/Item_4-1$/.test(n))this.equipComps['equip'+n.match(/^node(\d+)/)[1]]=x[key]}return x[key]};Layer.prototype.ref=function(){};
const out={};require(path.resolve(__dirname,'../../jojo_mobile/sgccz-desktop/recovered-js/modules/ui/UnitInfoLayer.js'))(n=>{if(n==='UILayer')return{default:Layer};if(n==='Config')return{ENABLED_FEATURE:{EDIT:1},GLOBAL_VAR:{QYWFGXXT:0},BATTLE_CAMP:{MINE:0,ENEMY:2},UNIT_ATTR_NAME2:{WL:0,YQ:4,INTRO:0}};if(n==='Model')return{default:{instance:()=>({getGVars:()=>featureEnabled?1:0,valueIsSingle:()=>false,skillIntro:()=>'',unitAttr:()=>'',money:()=>0})}};if(n==='Battle')return{default:{LAYER:{JiQiLayer:'JiQi',EditLayer:'Edit'}}};if(n==='Instance')return{default:{LAYER:{FeatsLayer:'Feats',ItemLayer:'Item',MagicLayer:'Magic'},format:s=>s}};return{default:{}}},{},out);
assert.ok(out.default,'original UnitInfoLayer export');const Source=out.default;for(const n of ['ref','_ref0','_ref1','_ref2','_ref3'])Source.prototype[n]=function(){};
function makeUnit(raw,id){const equips=(raw.equipment||[]).map(x=>x?{name:()=>x}:null),magics=(raw.magic||[]).map(x=>({name:()=>x,expendMp:()=>0,icon:()=>0}));return{id:()=>id,isMine:()=>raw.mine!==false,equip:n=>equips[n]||null,magics:()=>magics}}
function run(spec){featureEnabled=!!spec.featsEnabled;const layer=new Source;layer.editEnabled=!!spec.editEnabled;layer.m_ud.value=spec.defaultTab||0;const plain=(spec.units||[]).map(makeUnit),units=(spec.flag&1)?plain.map(u=>({unit:()=>u,magics:()=>u.magics()})):plain;layer.onCreate({units,index:spec.index||0,flag:spec.flag||0});const trace=[];function snap(step){const routes=layer.routes||[];layer.routes=[];trace.push({step,index:layer._index,selected:layer._sel,attached:!layer.removed,panels:layer._panels.map(x=>!!x.active),tabs:layer._btns.slice(0,5).map(x=>!!x.interactable),active:layer._btns.map(x=>!!x.node.active),routes})}function fire(raw){const[name,es]=raw.split(':'),event=+es;let c;if(name==='magic0'){c=layer.magicContent.children[0];layer._lastMagicRow=0}else if(name.startsWith('equip')){c=layer.equipComps[name];layer._lastEquipmentSlot=+name.slice(5)}else c=layer.buttonComps[name];const node=c&&(c.node||c);if(node&&node.active&&c.listener)c.listener(name==='magic0'?node:{node},event);snap(name+'-'+event)}snap('create');spec.events.forEach(fire);return{case:spec.id,trace}}
const result=fixture.cases.map(run);fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(result));console.log(JSON.stringify(result));
