#!/usr/bin/env node
/* Direct recovered-factory harness: ItemUpgradeLayer, StartItemLayer,
 * LearnUnitSkillLayer and the non-END EquipConfirm cancel branch. */
const fs=require('fs'),path=require('path'),F=JSON.parse(fs.readFileSync(process.argv[2]));
function N(){this.active=true;this.tag2=0;this._c=new Map();this.parent=null}
function Label(){this.node=new N();this.string=''} function Button(){this.node=new N();this.node.node=this.node;this.node.listener=(_,...args)=>this.listener(this,...args)}
function Edit(){this.node=new N();this.string=''} function Sprite(){this.node=new N()}
function Base(){this.n={};this.layers=[];this.events=[];this.dead=false;this.callbacks=0;this.m_manager={itemDir:x=>'i/'+x,addEvent(){}}}
Base.prototype._setBg=function(){}; Base.prototype.seekNodeByName=function(x,p){p=p||this;if(!p.n)p.n={};return p.n[x]||(p.n[x]=new N())};
Base.prototype.searchNodeByName=Base.prototype.seekNodeByName;
Base.prototype.seekCompByName=function(K,x,p){p=p||this.seekNodeByName(x);let k=K.name+x;if(!p._c.has(k)){let z=new K;z.node=p;p._c.set(k,z)}return p._c.get(k)};
Base.prototype.addTouchEventListener=function(n,h){n.listener=h}; Base.prototype.addLayer=function(layer,args){this.layers.push({layer,args:args?{txt:args.txt??null,flag:args.flag??null,sel:args.sel??null,listSize:args.list?.length??null}:null});this.answer=args&&(args.func||args.fn)};
Base.prototype.removeFromParent=function(){this.dead=true};Base.prototype.loadByUrl=function(f){f({ret:'sprite'})};Base.prototype.scheduleOnce=function(f){this.timer=f};Base.prototype.unschedule=function(f){if(this.timer===f)this.timer=null};
Base.prototype.dispatchEvent=function(name,value){this.events.push(name+':'+value)};
global.cc={_RF:{push(){},pop(){}},_decorator:{ccclass:x=>x,property:()=>()=>{}},Component:Base,Label,Button,EditBox:Edit,Sprite,SpriteFrame:class{},instantiate:n=>new N,color:(...x)=>x};
const C={UNIT_TIANFU:{UNIT0:0,POSTS:3,EFF_VALUE:4},UNIT_TIANFU_ZS:{UNIT_ID:0,ITEM_ID:1,EFF_VALUE:2},UNIT_TIANFU_TZ:{ITEM0:0,ITEM1:1,ITEM2:2,EFF_VALUE:3},UNIT_ATTR_NAME2:{NAME:0},POSTS_ATTR_NAME:{NAME:0},ITEM_ATTR_NAME:{NAME:0},UNIT_LIMIT:3,POSTS_COUNT_LIMIT:2,MAX_ITEM_COUNT_LIMIT:4,UNIT_POSTS_SKILL_OFFSET:0,UNIT_POSTS_SKILL_ATTR:{NAME:0}};
const Instance={default:{LAYER:{MsgBox:'MsgBox',SelectListLayer:'SelectListLayer'}}};
const skills={}; function key(...x){return x.join(':')};
const Model={default:{instance:()=>({cfgUnitAttrName:i=>'A'+i,skillAttr2:(s,a,d=0)=>skills[key('tf',s,a)]??(a===4?7:a===3?1:a),unitAttr2:(i,a,d='공백')=>'U'+i,postsAttr:(i,a,d='공백')=>'P'+i,getZSSkill:(s,z,a,d=0)=>skills[key('zs',s,z,a)]??(a===2?8:z+a),getTZSKill:(s,z,a,d=0)=>skills[key('tz',s,z,a)]??(a===3?9:z+a),itemAttr:(i,a,d='공백')=>'I'+i,setSkillAttr2:(s,a,v)=>{skills[key('tf',s,a)]=v;global.layer.events.push('tf:'+s+':'+a+':'+v)},setZSSkill:(s,z,a,v)=>{skills[key('zs',s,z,a)]=v;global.layer.events.push('zs:'+s+':'+z+':'+a+':'+v)},setTZSkill:(s,z,a,v)=>{skills[key('tz',s,z,a)]=v;global.layer.events.push('tz:'+s+':'+z+':'+a+':'+v)},skillIter:f=>[0,1].forEach(i=>f(i,['S'+i]))})}};
const Tool={default:{len:o=>Object.keys(o).length}};
function load(name){let ex={};require(path.resolve(__dirname,'../../jojo_mobile/sgccz-desktop/recovered-js/modules/ui/'+name+'.js'))(n=>({UILayer:{default:Base},Model,Config:C,Instance,Tool}[n]||{}),{},ex);return ex.default}
const Upgrade=load('ItemUpgradeLayer'),Start=load('StartItemLayer'),Learn=load('LearnUnitSkillLayer'),Confirm=load('EquipConfirmLayer');
function snap(l,step){return {step,dead:l.dead,active:l.node?.active??true,layers:l.layers.map(x=>x),events:[...l.events],callbacks:l.callbacks,skill:l._skillId??null,tf:Object.entries(l._modifyDataTF||{}),zs:Object.entries(l._modifyDataZS||{}),tz:Object.entries(l._modifyDataTZ||{})}}
function run(c){let l;if(c.kind==='upgrade'){l=new Upgrade();l.node=new N();global.layer=l;let q=c.item;l.onCreate({name:c.unit,item:{name:()=>q.name,lv:()=>q.lv,addAttrFlag:()=>q.flag,icon:()=>q.id},value:c.value,func:()=>l.callbacks++})}else if(c.kind==='start'){l=new Start();l.node=new N();global.layer=l;l.onCreate()}else if(c.kind==='learn'){l=new Learn();global.layer=l;l.onCreate()}else{l=new Confirm();global.layer=l;l.onCreate({values:c.values,func:()=>l.events.push('confirmed')})}let out=[snap(l,'create')];for(const e of c.events){let p=e.split(':');if(p[0]==='cancel'){l.seekNodeByName('Panel_cancel').listener?.({},+p[1])}else if(p[0]==='timer'){l.timer?.()}else if(p[0]==='choice'){let n=l.seekCompByName(Button,'bg1/button'+p[1]);n.node.tag2=+p[1];n.listener(n.node,+p[2])}else if(p[0]==='touch'){let n=l._btns[+p[1]];n.listener(n,+p[2])}else if(p[0]==='select'){let f=l.answer;l.answer=null;f?.(+p[1])}else if(p[0]==='skill'){l._items[+p[1]].listener(l._items[+p[1]],2)}else if(p[0]==='answer'){let f=l.answer;l.answer=null;f?.(+p[1])}else if(p[0]==='save'||p[0]==='close'){let n=l.seekNodeByName('Logo_12-1/button'+(p[0]==='save'?0:1));n.listener(n,+p[1])}else if(p[0]==='edit'){l._editChange=true;l.editingDidEnded({string:p[1]},{i:0,j:0})}else if(p[0]==='button'){let n=l.seekCompByName(Button,'button'+p[1],l.seekNodeByName('baseInfo'));n.node.tag2=+p[1];n.listener(n.node,+p[2])}out.push(snap(l,e))}return out}
fs.mkdirSync(path.dirname(process.argv[3]),{recursive:true});fs.writeFileSync(process.argv[3],JSON.stringify(Object.fromEntries(F.cases.map(c=>[c.name,run(c)]))));
